# Generated by Django 4.2.23 on 2025-06-25 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('facility', '0002_facilitylocation'),
        ('customer', '0006_customer_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='GRN Number')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('document_type', models.CharField(blank=True, choices=[('purchase_order', 'Purchase Order'), ('delivery_note', 'Delivery Note'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Supplier Name')),
                ('supplier_address', models.TextField(blank=True, verbose_name='Supplier Address')),
                ('supplier_phone', models.CharField(blank=True, max_length=50, verbose_name='Supplier Phone')),
                ('supplier_email', models.EmailField(blank=True, max_length=254, verbose_name='Supplier Email')),
                ('grn_date', models.DateField(default=django.utils.timezone.now, verbose_name='GRN Date')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Expected Date')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Received Date')),
                ('vessel', models.CharField(blank=True, max_length=100, verbose_name='Vessel')),
                ('voyage', models.CharField(blank=True, max_length=50, verbose_name='Voyage')),
                ('container_number', models.CharField(blank=True, max_length=50, verbose_name='Container Number')),
                ('seal_number', models.CharField(blank=True, max_length=50, verbose_name='Seal Number')),
                ('bl_number', models.CharField(blank=True, max_length=100, verbose_name='BL Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('total_packages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Packages')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Weight (KGS)')),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Volume (CBM)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grns', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility', verbose_name='Facility')),
            ],
            options={
                'verbose_name': 'Goods Received Note',
                'verbose_name_plural': 'Goods Received Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, verbose_name='Item Code')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='Item Name')),
                ('hs_code', models.CharField(blank=True, max_length=50, verbose_name='HS Code')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected Quantity')),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Received Quantity')),
                ('damaged_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Damaged Quantity')),
                ('short_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Short Quantity')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume')),
                ('coo', models.CharField(blank=True, max_length=3, verbose_name='Country of Origin')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grn.grn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'GRN Item',
                'verbose_name_plural': 'GRN Items',
                'unique_together': {('grn', 'item')},
            },
        ),
    ]
