# Generated by Django 4.2.23 on 2025-06-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobcontainer'),
        ('grn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='job_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job', verbose_name='Job Reference'),
        ),
    ]
