# Generated by Django 4.2.23 on 2025-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_grn_job_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer Reference'),
        ),
        migrations.AddField(
            model_name='grn',
            name='mode',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Land', 'Land'), ('Air', 'Air')], default='Sea', max_length=10, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='grn',
            name='total_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Quantity'),
        ),
    ]
