# Generated by Django 4.2.23 on 2025-06-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_alter_salesman_phone'),
        ('grn', '0003_grn_customer_ref_grn_mode_grn_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grns', to='salesman.salesman', verbose_name='Assigned To'),
        ),
    ]
