# Generated by Django 4.2.23 on 2025-06-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0004_alter_grn_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='title',
        ),
    ]
