# Generated by Django 4.2.23 on 2025-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0005_remove_grn_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='grn',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver Name'),
        ),
        migrations.AddField(
            model_name='grn',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vehicle Number'),
        ),
    ]
