# Generated by Django 4.2.23 on 2025-06-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('grn', '0006_grn_contact_no_grn_driver_name_grn_vehicle_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grnitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item'),
        ),
    ]
