# Generated by Django 4.2.23 on 2025-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0007_alter_grnitem_unique_together_alter_grnitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='ctnr',
            field=models.CharField(blank=True, max_length=50, verbose_name='CTNR'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='ed',
            field=models.CharField(blank=True, max_length=50, verbose_name='ED'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='p_date',
            field=models.DateField(blank=True, null=True, verbose_name='P-Date'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Size'),
        ),
    ]
