# Generated by Django 4.2.23 on 2025-06-26 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('grn', '0008_grnitem_color_grnitem_ctnr_grnitem_ed_grnitem_p_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_no', models.CharField(max_length=100, verbose_name='Pallet Number')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (KGS)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (CBM)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('in_transit', 'In Transit'), ('stored', 'Stored')], default='pending', max_length=20, verbose_name='Status')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='grn.grn', verbose_name='GRN')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'GRN Pallet',
                'verbose_name_plural': 'GRN Pallets',
                'ordering': ['pallet_no'],
            },
        ),
    ]
