# Generated by Django 4.2.23 on 2025-06-20 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_code', models.CharField(help_text='Unique port code (e.g., JED, DXB)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Port code must contain only uppercase letters and numbers.')])),
                ('port_name', models.CharField(help_text='Full name of the port', max_length=100)),
                ('port_type', models.CharField(choices=[('seaport', 'Sea Port'), ('airport', 'Air Port'), ('dryport', 'Dry Port'), ('inland', 'Inland Port')], default='seaport', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('customs_office', models.CharField(blank=True, max_length=100)),
                ('customs_phone', models.CharField(blank=True, max_length=20)),
                ('max_vessel_size', models.CharField(blank=True, help_text='Maximum vessel size in TEU or DWT', max_length=50)),
                ('berth_count', models.PositiveIntegerField(default=0)),
                ('container_capacity', models.PositiveIntegerField(default=0, help_text='Container capacity in TEU')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('handling_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
                'db_table': 'port',
                'ordering': ['port_name'],
            },
        ),
    ]
