# Generated by Django 4.2.23 on 2025-06-21 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_alter_customer_portal_username'),
        ('items', '0002_remove_item_item_type_item_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0002_facilitylocation'),
        ('salesman', '0002_alter_salesman_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(help_text='Unique quotation number', max_length=20, unique=True)),
                ('subject', models.CharField(help_text='Quotation subject/title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of services')),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(help_text='Quotation validity period')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='AED', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customer.customer')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='facility.facility')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='salesman.salesman')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item description', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='items.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='quotation.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
            },
        ),
    ]
