# Generated by Django 4.2.23 on 2025-06-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
    ]
