# Generated by Django 4.2.23 on 2025-06-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('quotation', '0002_auto_20250621_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': 'Quotation Service', 'verbose_name_plural': 'Quotation Services'},
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='service.service'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(help_text='Service description', max_length=500),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this service'),
        ),
    ]
