# Generated by Django 4.2.23 on 2025-06-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('quotation', '0003_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='service.service'),
        ),
    ]
