# Generated by Django 4.2.23 on 2025-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_alter_quotationitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional tax amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='VAT amount (5%)', max_digits=12),
        ),
    ]
