# Generated by Django 4.2.23 on 2025-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_quotation_additional_tax_amount_quotation_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='vat_applied',
            field=models.BooleanField(default=False, help_text='Whether VAT was applied to this item'),
        ),
    ]
