# Generated by Django 4.2.23 on 2025-07-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0007_add_supplier_customer_type'),
        ('invoice', '0008_invoice_bill_to_invoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('friendly', 'Friendly Reminder'), ('firm', 'Firm Reminder'), ('final', 'Final Notice')], default='friendly', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overdue_days', models.IntegerField()),
                ('due_date', models.DateField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_letters', to='customer.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_letters', to='invoice.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'invoice', 'level')},
            },
        ),
    ]
