# Generated by Django 4.2.23 on 2025-06-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('dispatchnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchitem',
            options={'ordering': ['item_name'], 'verbose_name': 'Dispatch Item', 'verbose_name_plural': 'Dispatch Items'},
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='delivery_contact',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='delivery_email',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='delivery_phone',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='dispatch_number',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='cbm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='coo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='e_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='ed_cntr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='g_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='grn_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='hs_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='n_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='p_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='deliver_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='deliver_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='facility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='gdn_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item'),
        ),
    ]
