# Generated by Django 4.2.23 on 2025-06-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0003_alter_deliveryorder_delivery_address'),
        ('dispatchnote', '0002_alter_dispatchitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchnote',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_order.deliveryorder', verbose_name='Delivery Order'),
        ),
    ]
