# Generated by Django 4.2.23 on 2025-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchnote', '0003_dispatchnote_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='ctnr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='ed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
