# Generated by Django 4.2.23 on 2025-07-09 08:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi_currency', '0001_initial'),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('transfer_type', models.CharField(choices=[('internal', 'Internal Transfer'), ('external', 'External Transfer'), ('interbank', 'Interbank Transfer')], default='internal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate if different currencies', max_digits=10)),
                ('converted_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in target currency', max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_cancelled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency')),
                ('from_account', models.ForeignKey(limit_choices_to={'account_type__category': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='chart_of_accounts.chartofaccount')),
                ('to_account', models.ForeignKey(limit_choices_to={'account_type__category': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='chart_of_accounts.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('default_narration', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('default_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multi_currency.currency')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_templates_from', to='chart_of_accounts.chartofaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_templates_to', to='chart_of_accounts.chartofaccount')),
            ],
            options={
                'verbose_name': 'Bank Transfer Template',
                'verbose_name_plural': 'Bank Transfer Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='bank_transfer.banktransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transfer Audit',
                'verbose_name_plural': 'Bank Transfer Audits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
