# Generated by Django 4.2.23 on 2025-07-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_currency', '0001_initial'),
        ('bank_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency'),
        ),
        migrations.AlterField(
            model_name='banktransfertemplate',
            name='default_currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='multi_currency.currency'),
        ),
    ]
