# Generated by Django 4.2.23 on 2025-06-24 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0002_facilitylocation'),
        ('customer', '0006_customer_salesman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_jobcontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossStuffing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_number', models.CharField(max_length=20, unique=True, verbose_name='CS Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cs_date', models.DateField(default=django.utils.timezone.now, verbose_name='CS Date')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('container_number', models.CharField(max_length=20, verbose_name='Container Number')),
                ('container_size', models.CharField(choices=[('20', '20ft'), ('40', '40ft'), ('40HC', '40ft HC'), ('45', '45ft')], max_length=10, verbose_name='Container Size')),
                ('container_type', models.CharField(choices=[('GP', 'General Purpose'), ('RF', 'Reefer'), ('OT', 'Open Top'), ('FR', 'Flat Rack'), ('TK', 'Tank')], max_length=20, verbose_name='Container Type')),
                ('cargo_description', models.TextField(verbose_name='Cargo Description')),
                ('total_packages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Packages')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Weight (KGS)')),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Volume (CBM)')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges')),
                ('currency', models.CharField(choices=[('AED', 'AED'), ('USD', 'USD'), ('EUR', 'EUR')], default='AED', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crossstuffing', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crossstuffing', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility', verbose_name='Facility')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Related Job')),
            ],
            options={
                'verbose_name': 'Cross Stuffing',
                'verbose_name_plural': 'Cross Stuffings',
                'ordering': ['-created_at'],
            },
        ),
    ]
