# Generated by Django 4.2.23 on 2025-06-24 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
        ('crossstuffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossstuffing',
            name='bill_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bill To'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='bill_to_address',
            field=models.TextField(blank=True, verbose_name='Bill to Address'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='bl_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='BL Number'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='boe',
            field=models.CharField(blank=True, max_length=50, verbose_name='BOE'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='deliver_to_address',
            field=models.TextField(blank=True, verbose_name='Deliver to Address'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Delivery Terms'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='destination',
            field=models.CharField(blank=True, choices=[('UAE', 'United Arab Emirates'), ('SAU', 'Saudi Arabia'), ('KWT', 'Kuwait'), ('QAT', 'Qatar'), ('BHR', 'Bahrain'), ('OMN', 'Oman'), ('USA', 'United States'), ('GBR', 'United Kingdom'), ('DEU', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('NLD', 'Netherlands'), ('BEL', 'Belgium'), ('CHE', 'Switzerland'), ('AUT', 'Austria'), ('SWE', 'Sweden'), ('NOR', 'Norway'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('CHN', 'China'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('IND', 'India'), ('PAK', 'Pakistan'), ('BGD', 'Bangladesh'), ('LKA', 'Sri Lanka'), ('THA', 'Thailand'), ('VNM', 'Vietnam'), ('MYS', 'Malaysia'), ('SGP', 'Singapore'), ('IDN', 'Indonesia'), ('PHL', 'Philippines'), ('AUS', 'Australia'), ('NZL', 'New Zealand'), ('CAN', 'Canada'), ('MEX', 'Mexico'), ('BRA', 'Brazil'), ('ARG', 'Argentina'), ('CHL', 'Chile'), ('COL', 'Colombia'), ('PER', 'Peru'), ('VEN', 'Venezuela'), ('ZAF', 'South Africa'), ('EGY', 'Egypt'), ('MAR', 'Morocco'), ('TUN', 'Tunisia'), ('ALG', 'Algeria'), ('LBY', 'Libya'), ('SDN', 'Sudan'), ('ETH', 'Ethiopia'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('GHA', 'Ghana'), ('CIV', 'Ivory Coast'), ('SEN', 'Senegal'), ('MLI', 'Mali'), ('BFA', 'Burkina Faso'), ('NER', 'Niger'), ('TCD', 'Chad'), ('CMR', 'Cameroon'), ('GAB', 'Gabon'), ('COG', 'Republic of the Congo'), ('COD', 'Democratic Republic of the Congo'), ('CAF', 'Central African Republic'), ('TZA', 'Tanzania'), ('UGA', 'Uganda'), ('RWA', 'Rwanda'), ('BDI', 'Burundi'), ('MWI', 'Malawi'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe'), ('BWA', 'Botswana'), ('NAM', 'Namibia'), ('LSO', 'Lesotho'), ('SWZ', 'Eswatini'), ('MDG', 'Madagascar'), ('MUS', 'Mauritius'), ('SYC', 'Seychelles'), ('COM', 'Comoros'), ('DJI', 'Djibouti'), ('SOM', 'Somalia'), ('ERI', 'Eritrea'), ('SSD', 'South Sudan'), ('RUS', 'Russia'), ('UKR', 'Ukraine'), ('BLR', 'Belarus'), ('POL', 'Poland'), ('CZE', 'Czech Republic'), ('SVK', 'Slovakia'), ('HUN', 'Hungary'), ('ROU', 'Romania'), ('BGR', 'Bulgaria'), ('HRV', 'Croatia'), ('SVN', 'Slovenia'), ('BIH', 'Bosnia and Herzegovina'), ('SRB', 'Serbia'), ('MNE', 'Montenegro'), ('MKD', 'North Macedonia'), ('ALB', 'Albania'), ('GRC', 'Greece'), ('TUR', 'Turkey'), ('CYP', 'Cyprus'), ('MLT', 'Malta'), ('ISL', 'Iceland'), ('IRL', 'Ireland'), ('PRT', 'Portugal'), ('LUX', 'Luxembourg'), ('LIE', 'Liechtenstein'), ('MCO', 'Monaco'), ('AND', 'Andorra'), ('SMR', 'San Marino'), ('VAT', 'Vatican City')], max_length=3, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='discharge_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_crossstuffing', to='port.port', verbose_name='Discharge Port'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='document_type',
            field=models.CharField(blank=True, choices=[('TOO', 'TOO'), ('TRANSIT_OUT', 'Transit Out'), ('IMPORT_LOCAL', 'Import to local from FZ')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='exit_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_crossstuffing', to='port.port', verbose_name='Exit Point'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TT', 'Bank TT'), ('CREDIT', 'Credit')], max_length=20, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='port_of_loading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_crossstuffing', to='port.port', verbose_name='Port of Loading'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='ship_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ship Date'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='ship_mode',
            field=models.CharField(blank=True, choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], max_length=20, verbose_name='Ship Mode'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vessel'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='voyage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='container_number',
            field=models.CharField(max_length=20, verbose_name='Container'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='cs_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
