# Generated by Django 4.2.23 on 2025-06-25 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facilitylocation'),
        ('job', '0012_jobcontainer'),
        ('crossstuffing', '0002_crossstuffing_bill_to_crossstuffing_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossstuffing',
            name='cargo_description',
            field=models.TextField(blank=True, verbose_name='Cargo Description'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20', '20ft'), ('40', '40ft'), ('40HC', '40ft HC'), ('45', '45ft')], max_length=10, verbose_name='Container Size'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='container_type',
            field=models.CharField(blank=True, choices=[('GP', 'General Purpose'), ('RF', 'Reefer'), ('OT', 'Open Top'), ('FR', 'Flat Rack'), ('TK', 'Tank')], max_length=20, verbose_name='Container Type'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Related Job'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='total_packages',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Packages'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Volume (CBM)'),
        ),
        migrations.AlterField(
            model_name='crossstuffing',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Weight (KGS)'),
        ),
    ]
