# Generated by Django 4.2.23 on 2025-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossstuffing', '0003_alter_crossstuffing_cargo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossstuffing',
            name='cs_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='CS Number'),
        ),
    ]
