# Generated by Django 4.2.23 on 2025-06-25 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobcontainer'),
        ('crossstuffing', '0004_alter_crossstuffing_cs_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossStuffingCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight')),
                ('ed_number', models.CharField(blank=True, max_length=50, verbose_name='ED Number')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crossstuffing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='crossstuffing.crossstuffing')),
                ('job_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossstuffing_items', to='job.jobcargo')),
            ],
            options={
                'verbose_name': 'Cross Stuffing Cargo Item',
                'verbose_name_plural': 'Cross Stuffing Cargo Items',
                'unique_together': {('crossstuffing', 'job_cargo')},
            },
        ),
    ]
