# Generated by Django 4.2.23 on 2025-06-25 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossstuffing', '0005_crossstuffingcargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossStuffingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(blank=True, max_length=50, verbose_name='Job No')),
                ('items', models.CharField(blank=True, max_length=200, verbose_name='Items')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qty')),
                ('imp_cntr', models.CharField(blank=True, max_length=50, verbose_name='Imp CNTR')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Size')),
                ('seal', models.CharField(blank=True, max_length=50, verbose_name='Seal')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crossstuffing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_items', to='crossstuffing.crossstuffing')),
            ],
            options={
                'verbose_name': 'Cross Stuffing Summary Item',
                'verbose_name_plural': 'Cross Stuffing Summary Items',
                'ordering': ['created_at'],
            },
        ),
    ]
