# Generated by Django 5.0.2 on 2025-08-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossstuffing', '0006_crossstuffingsummary'),
        ('customer', '0007_add_supplier_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossstuffing',
            name='bill_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossstuffing_as_bill_to', to='customer.customer', verbose_name='Bill To Customer'),
        ),
        migrations.AddField(
            model_name='crossstuffing',
            name='deliver_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossstuffing_as_deliver_to', to='customer.customer', verbose_name='Deliver To Customer'),
        ),
    ]
