# Generated by Django 5.0.2 on 2025-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossstuffing', '0007_crossstuffing_bill_to_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossstuffingsummary',
            name='exp_cntr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Exp CNTR'),
        ),
        migrations.AddField(
            model_name='crossstuffingsummary',
            name='exp_seal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Exp Seal'),
        ),
        migrations.AddField(
            model_name='crossstuffingsummary',
            name='exp_size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Exp Size'),
        ),
    ]
