# Generated by Django 4.2.23 on 2025-07-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_company_company_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('show_revenue_section', models.BooleanField(default=True)),
                ('show_cogs_section', models.BooleanField(default=True)),
                ('show_expenses_section', models.BooleanField(default=True)),
                ('show_other_income_expenses', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#1e3a8a', max_length=7)),
                ('secondary_color', models.CharField(default='#6b7280', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('group_by_department', models.BooleanField(default=False)),
                ('group_by_cost_center', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('report_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Period')], default='custom', max_length=20)),
                ('comparison_type', models.CharField(choices=[('none', 'No Comparison'), ('previous_period', 'Previous Period'), ('previous_year', 'Previous Year'), ('budget', 'Budget Comparison')], default='none', max_length=20)),
                ('report_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_headers', models.BooleanField(default=True)),
                ('include_totals', models.BooleanField(default=True)),
                ('include_comparison', models.BooleanField(default=False)),
                ('currency_format', models.CharField(default='AED', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profit & Loss Report',
                'verbose_name_plural': 'Profit & Loss Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
