# Generated by Django 4.2.23 on 2025-08-07 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight_quotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_extension', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('shipment_type', models.CharField(choices=[('fcl', 'FCL (Full Container Load)'), ('lcl', 'LCL (Less than Container Load)'), ('air', 'Air Freight'), ('land', 'Land Transport'), ('express', 'Express')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('origin_country', models.CharField(max_length=100)),
                ('origin_port', models.CharField(blank=True, max_length=100)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_port', models.CharField(blank=True, max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('cargo_description', models.TextField()),
                ('commodity', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packages', models.PositiveIntegerField(default=1)),
                ('container_type', models.CharField(blank=True, choices=[('20ft', '20ft Standard'), ('40ft', '40ft Standard'), ('40hc', '40ft High Cube'), ('45ft', '45ft High Cube'), ('reefer', 'Reefer Container'), ('open_top', 'Open Top'), ('flat_rack', 'Flat Rack'), ('tank', 'Tank Container')], max_length=20)),
                ('container_count', models.PositiveIntegerField(default=0)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('transit_start_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('special_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight_booking.bookingcoordinator')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_booking.carrier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_quotation.customer')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight_quotation.freightquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('document_added', 'Document Added'), ('document_removed', 'Document Removed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='freight_booking.freightbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booking history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('msds', 'MSDS (Material Safety Data Sheet)'), ('certificate_of_origin', 'Certificate of Origin'), ('bill_of_lading', 'Bill of Lading'), ('airway_bill', 'Airway Bill'), ('customs_declaration', 'Customs Declaration'), ('insurance_certificate', 'Insurance Certificate'), ('other', 'Other')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='booking_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='freight_booking.freightbooking')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('freight', 'Freight Cost'), ('handling', 'Handling Charges'), ('customs', 'Customs Charges'), ('insurance', 'Insurance'), ('storage', 'Storage Charges'), ('detention', 'Detention Charges'), ('demurrage', 'Demurrage Charges'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='freight_booking.freightbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
