# Generated by Django 4.2.23 on 2025-08-12 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(help_text='Path to the document file', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('page_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('erp_reference', models.CharField(blank=True, help_text='Reference from ERP system', max_length=100)),
                ('erp_module', models.CharField(blank=True, help_text='ERP module source', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional document metadata')),
                ('is_public', models.BooleanField(default=False, help_text='Publicly accessible')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='User roles that can access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('delivery_note', 'Delivery Note'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('receipt', 'Receipt'), ('report', 'Report'), ('contract', 'Contract'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Requires approval before preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PreviewSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_zoom', models.FloatField(default=1.0, help_text='Default zoom level')),
                ('default_page_layout', models.CharField(choices=[('single', 'Single Page'), ('continuous', 'Continuous'), ('facing', 'Facing Pages')], default='single', max_length=20)),
                ('enable_thumbnails', models.BooleanField(default=True)),
                ('enable_search', models.BooleanField(default=True)),
                ('enable_annotations', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('hidden', 'Hidden')], default='left', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preview Settings',
                'verbose_name_plural': 'Preview Settings',
            },
        ),
        migrations.CreateModel(
            name='PreviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Session duration in seconds', null=True)),
                ('pages_viewed', models.JSONField(blank=True, default=list, help_text='List of pages viewed')),
                ('zoom_levels_used', models.JSONField(blank=True, default=list, help_text='Zoom levels used during session')),
                ('search_queries', models.JSONField(blank=True, default=list, help_text='Search queries performed')),
                ('downloads_count', models.IntegerField(default=0)),
                ('print_count', models.IntegerField(default=0)),
                ('email_count', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to='pdf_preview_tool.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preview Session',
                'verbose_name_plural': 'Preview Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('view_page', 'View Page'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('search', 'Search'), ('download', 'Download'), ('print', 'Print'), ('email', 'Email'), ('rotate', 'Rotate'), ('scroll', 'Scroll'), ('bookmark', 'Bookmark')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Action-specific details')),
                ('page_number', models.IntegerField(blank=True, help_text='Page where action occurred', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pdf_preview_tool.previewsession')),
            ],
            options={
                'verbose_name': 'Preview Action',
                'verbose_name_plural': 'Preview Actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('preview', 'Preview'), ('download', 'Download'), ('print', 'Print'), ('email', 'Email'), ('denied', 'Access Denied')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for access or denial')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='pdf_preview_tool.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pdf_preview_tool.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
