# Generated by Django 5.0.2 on 2025-08-17 13:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pdf_preview_tool.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_preview_tool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentaccesslog',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='previewaction',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='browser_info',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='downloads_count',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='email_count',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='pages_viewed',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='print_count',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='search_queries',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='previewsession',
            name='zoom_levels_used',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='browser_notifications',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='default_page_layout',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='enable_search',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='enable_thumbnails',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='sidebar_position',
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='previewsession',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='auto_fit_page',
            field=models.BooleanField(default=True, help_text='Auto-fit page to viewport'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='show_thumbnails',
            field=models.BooleanField(default=True, help_text='Show page thumbnails by default'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='access_type',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print'), ('share', 'Share')], max_length=20),
        ),
        migrations.AlterField(
            model_name='previewaction',
            name='action_type',
            field=models.CharField(choices=[('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('page_nav', 'Page Navigation'), ('download', 'Download'), ('print', 'Print'), ('share', 'Share'), ('comment', 'Comment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='previewaction',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='default_zoom',
            field=models.FloatField(default=100.0, help_text='Default zoom percentage'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='enable_annotations',
            field=models.BooleanField(default=False, help_text='Enable annotation tools'),
        ),
        migrations.CreateModel(
            name='SignatureStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Upload PNG, JPG, or JPEG image (max 2MB)', upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), pdf_preview_tool.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_stamp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature/Stamp',
                'verbose_name_plural': 'Signatures/Stamps',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
