# Generated by Django 4.2.23 on 2025-08-09 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('currency', models.CharField(choices=[('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='AED', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_trn', models.CharField(blank=True, max_length=50)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('customer_trn', models.CharField(blank=True, max_length=50)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_invoices', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Invoice',
                'verbose_name_plural': 'Tax Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('standard', 'Standard'), ('detailed', 'Detailed'), ('minimal', 'Minimal'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('include_logo', models.BooleanField(default=True)),
                ('include_qr_code', models.BooleanField(default=False)),
                ('include_bank_details', models.BooleanField(default=True)),
                ('include_terms', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=50)),
                ('header_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Invoice Template',
                'verbose_name_plural': 'Tax Invoice Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_company_name', models.CharField(blank=True, max_length=200)),
                ('default_company_address', models.TextField(blank=True)),
                ('default_company_trn', models.CharField(blank=True, max_length=50)),
                ('default_company_phone', models.CharField(blank=True, max_length=20)),
                ('default_company_email', models.EmailField(blank=True, max_length=254)),
                ('default_company_website', models.URLField(blank=True)),
                ('default_currency', models.CharField(choices=[('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='AED', max_length=3)),
                ('default_payment_terms', models.IntegerField(default=30)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('pdf_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('pdf_page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('email_subject_template', models.CharField(default='Tax Invoice {invoice_number} from {company_name}', max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('require_customer_trn', models.BooleanField(default=False)),
                ('require_vat_number', models.BooleanField(default=True)),
                ('validate_vat_rates', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_invoice.taxinvoicetemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Invoice Settings',
                'verbose_name_plural': 'Tax Invoice Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tax_invoice.taxinvoice')),
            ],
            options={
                'verbose_name': 'Tax Invoice Item',
                'verbose_name_plural': 'Tax Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('email', 'Email')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='tax_invoice.taxinvoice')),
            ],
            options={
                'verbose_name': 'Tax Invoice Export',
                'verbose_name_plural': 'Tax Invoice Exports',
                'ordering': ['-exported_at'],
            },
        ),
    ]
