# Generated by Django 4.2.23 on 2025-06-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grn', '0009_grnpallet'),
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('facility', '0002_facilitylocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Putaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('putaway_number', models.CharField(max_length=50, unique=True, verbose_name='Putaway Number')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('pallet_id', models.CharField(max_length=100, verbose_name='Pallet ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('putaway_date', models.DateTimeField(auto_now_add=True, verbose_name='Putaway Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaways_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grn.grn', verbose_name='GRN')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facilitylocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Putaway',
                'verbose_name_plural': 'Putaways',
                'ordering': ['-created_at'],
            },
        ),
    ]
