# Generated by Django 4.2.23 on 2025-08-07 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0007_add_supplier_customer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('container_number', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hbl_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('expected_departure', models.DateField(blank=True, null=True)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('actual_departure', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('at_origin_port', 'At Origin Port'), ('sailing', 'Sailing'), ('arrived_destination', 'Arrived at Destination Port'), ('customs_cleared', 'Customs Cleared'), ('delivered', 'Delivered'), ('on_hold', 'On Hold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='at_origin_port', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vessel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voyage_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_line', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_description', models.TextField(blank=True, null=True)),
                ('cargo_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_tracking_enabled', models.BooleanField(default=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('at_origin_port', 'At Origin Port'), ('sailing', 'Sailing'), ('arrived_destination', 'Arrived at Destination Port'), ('customs_cleared', 'Customs Cleared'), ('delivered', 'Delivered'), ('on_hold', 'On Hold'), ('damaged', 'Damaged'), ('returned', 'Returned')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='shipment_tracking.shipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Update',
                'verbose_name_plural': 'Status Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=200)),
                ('search_type', models.CharField(choices=[('container', 'Container Number'), ('booking', 'Booking ID'), ('hbl', 'HBL Number'), ('customer_ref', 'Customer Reference'), ('general', 'General Search')], max_length=20)),
                ('search_results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment Search',
                'verbose_name_plural': 'Shipment Searches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shipment_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('file_type', models.CharField(choices=[('pod', 'Proof of Delivery'), ('photo', 'Photo'), ('gate_pass', 'Gate Pass'), ('customs_doc', 'Customs Document'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shipment_tracking.shipment')),
                ('status_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shipment_tracking.statusupdate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment Attachment',
                'verbose_name_plural': 'Shipment Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('system', 'System Notification')], max_length=20)),
                ('recipient', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipment_tracking.shipment')),
                ('status_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipment_tracking.statusupdate')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('excel_upload', 'Excel Upload'), ('api_update', 'API Update'), ('manual_bulk', 'Manual Bulk Update')], max_length=20)),
                ('file_uploaded', models.FileField(blank=True, null=True, upload_to='bulk_updates/%Y/%m/%d/')),
                ('total_records', models.IntegerField(default=0)),
                ('successful_updates', models.IntegerField(default=0)),
                ('failed_updates', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('success_details', models.JSONField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Update Log',
                'verbose_name_plural': 'Bulk Update Logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
