# Generated by Django 5.0.2 on 2025-08-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportlog',
            options={'ordering': ['-created_at'], 'permissions': [('can_export_data', 'Can export data'), ('can_view_export_logs', 'Can view export logs')], 'verbose_name': 'Export Log', 'verbose_name_plural': 'Export Logs'},
        ),
    ]
