# Generated by Django 4.2.23 on 2025-08-04 10:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_item_cbm_item_country_of_origin_item_gross_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_add_supplier_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('per_cbm_days', 'Per CBM/Days'), ('per_sqmts_days', 'Per SQMTS/Days'), ('per_weight_days', 'Per Weight/Days'), ('fixed', 'Fixed'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Charge Type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Rate')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='customer.customer', verbose_name='Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='items.item', verbose_name='Item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-effective_date', 'customer__customer_name', 'item__item_name'],
                'indexes': [models.Index(fields=['customer', 'item'], name='charges_cha_custome_58f6d4_idx'), models.Index(fields=['charge_type'], name='charges_cha_charge__f80692_idx'), models.Index(fields=['effective_date'], name='charges_cha_effecti_5c6e7d_idx'), models.Index(fields=['status'], name='charges_cha_status_7d1ed6_idx')],
                'unique_together': {('customer', 'item', 'charge_type', 'effective_date')},
            },
        ),
    ]
