services:
  - type: web
    name: logisedge
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT logisEdge.wsgi:application"
    plan: free
    healthCheckPath: /admin/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: logisedge.onrender.com,localhost,127.0.0.1
      - key: DB_ENV
        value: external
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: SECRET_KEY
        generateValue: true