# Generated by Django 4.2.23 on 2025-08-11 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Category',
                'verbose_name_plural': 'Log Categories',
                'db_table': 'log_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(blank=True, choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('STATUS_CHANGE', 'Status Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('ROLE_CHANGE', 'Role Change'), ('SYSTEM', 'System'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('retention_period', models.IntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year'), (730, '2 Years'), (1825, '5 Years'), (3650, '10 Years'), (-1, 'Forever')], default=365)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Retention Policy',
                'verbose_name_plural': 'Log Retention Policies',
                'db_table': 'log_retention_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('XML', 'XML'), ('PDF', 'PDF')], max_length=10)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Export',
                'verbose_name_plural': 'Log Exports',
                'db_table': 'log_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('STATUS_CHANGE', 'Status Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('ROLE_CHANGE', 'Role Change'), ('SYSTEM', 'System'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user_session', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('memory_usage', models.BigIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log History Entry',
                'verbose_name_plural': 'Log History Entries',
                'db_table': 'log_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action_type'], name='log_history_timesta_54f3c3_idx'), models.Index(fields=['user', 'timestamp'], name='log_history_user_id_560003_idx'), models.Index(fields=['content_type', 'object_id'], name='log_history_content_41f7c2_idx'), models.Index(fields=['severity', 'timestamp'], name='log_history_severit_36567e_idx'), models.Index(fields=['module', 'timestamp'], name='log_history_module_20a444_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Filter',
                'verbose_name_plural': 'Log Filters',
                'db_table': 'log_filters',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
