# Generated by Django 4.2.23 on 2025-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOETransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_no', models.CharField(max_length=100, verbose_name='Declaration No')),
                ('bill_no', models.CharField(max_length=100, verbose_name='Bill No')),
                ('date', models.DateField(verbose_name='Date')),
                ('hs_code', models.CharField(max_length=50, verbose_name='HS Code')),
                ('particulars', models.CharField(max_length=255, verbose_name='Particulars')),
                ('cog', models.CharField(max_length=100, verbose_name='COG')),
                ('pkg_type', models.CharField(max_length=50, verbose_name='Package Type')),
                ('qty_in', models.IntegerField(default=0, verbose_name='Quantity In')),
                ('wt_in', models.FloatField(default=0.0, verbose_name='Weight In')),
                ('value_in', models.FloatField(default=0.0, verbose_name='Value In')),
                ('qty_out', models.IntegerField(default=0, verbose_name='Quantity Out')),
                ('wt_out', models.FloatField(default=0.0, verbose_name='Weight Out')),
                ('value_out', models.FloatField(default=0.0, verbose_name='Value Out')),
                ('duty', models.FloatField(default=0.0, verbose_name='Duty')),
                ('total_dues', models.FloatField(default=0.0, verbose_name='Total Dues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BOE Transaction',
                'verbose_name_plural': 'BOE Transactions',
                'db_table': 'customs_boe_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
