# Generated by Django 4.2.23 on 2025-08-12 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPrintRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Printing conditions (warehouse, customer type, etc.)')),
                ('batch_printing', models.BooleanField(default=False, help_text='Enable batch printing')),
                ('batch_schedule', models.CharField(blank=True, help_text='Cron expression for batch schedule', max_length=100)),
                ('preview_required', models.BooleanField(default=False, help_text='Show preview before printing')),
                ('auto_print', models.BooleanField(default=True, help_text='Print automatically without user intervention')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts')),
                ('retry_delay', models.IntegerField(default=300, help_text='Delay between retries in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auto_print_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Print Rule',
                'verbose_name_plural': 'Auto Print Rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('printer_type', models.CharField(choices=[('physical', 'Physical Printer'), ('virtual', 'Virtual Printer'), ('network', 'Network Printer'), ('cloud', 'Cloud Printer')], default='physical', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, default=9100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_job_size', models.IntegerField(default=100, help_text='Maximum jobs in queue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_printers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_printers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('load_balancing', models.BooleanField(default=True, help_text='Distribute jobs across printers')),
                ('failover', models.BooleanField(default=True, help_text='Failover to next available printer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_printer_groups', to=settings.AUTH_USER_MODEL)),
                ('printers', models.ManyToManyField(related_name='printer_groups', to='print_queue_management.printer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_printer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer Group',
                'verbose_name_plural': 'Printer Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(help_text='Human-readable job number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='queued', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Template data for printing')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated print file', max_length=500)),
                ('pages', models.IntegerField(default=1)),
                ('copies', models.IntegerField(default=1)),
                ('preview_required', models.BooleanField(default=False)),
                ('preview_generated', models.BooleanField(default=False)),
                ('preview_file', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_print_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='print_queue_management.autoprintrule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice'), ('packing_slip', 'Packing Slip'), ('grn', 'Goods Received Note'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('delivery_order', 'Delivery Order'), ('receipt', 'Receipt'), ('custom', 'Custom Template')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(blank=True, upload_to='print_templates/')),
                ('template_content', models.TextField(blank=True, help_text='Template content or HTML')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Template variables and placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_print_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_print_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Template',
                'verbose_name_plural': 'Print Templates',
                'ordering': ['template_type', 'name'],
                'unique_together': {('template_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PrintJobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retried', 'Retried'), ('preview_generated', 'Preview Generated')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='print_queue_management.printjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_job_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Job Log',
                'verbose_name_plural': 'Print Job Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='printjob',
            name='print_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='print_queue_management.printtemplate'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='print_queue_management.printer'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='print_queue_management.printergroup'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_print_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ERPEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(choices=[('sales_order_approved', 'Sales Order Approved'), ('delivery_order_dispatched', 'Delivery Order Dispatched'), ('goods_received', 'Goods Received'), ('invoice_generated', 'Invoice Generated'), ('payment_received', 'Payment Received'), ('purchase_order_created', 'Purchase Order Created'), ('inventory_adjusted', 'Inventory Adjusted'), ('custom', 'Custom Event')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('event_code', models.CharField(help_text='Unique event identifier', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_erp_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_erp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP Event',
                'verbose_name_plural': 'ERP Events',
                'ordering': ['event_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BatchPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('total_jobs', models.IntegerField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('failed_jobs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_print_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='print_queue_management.autoprintrule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batch_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Print Job',
                'verbose_name_plural': 'Batch Print Jobs',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='autoprintrule',
            name='erp_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_print_rules', to='print_queue_management.erpevent'),
        ),
        migrations.AddField(
            model_name='autoprintrule',
            name='print_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_print_rules', to='print_queue_management.printtemplate'),
        ),
        migrations.AddField(
            model_name='autoprintrule',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_print_rules', to='print_queue_management.printer'),
        ),
        migrations.AddField(
            model_name='autoprintrule',
            name='printer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_print_rules', to='print_queue_management.printergroup'),
        ),
        migrations.AddField(
            model_name='autoprintrule',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_auto_print_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
