# Generated by Django 4.2.23 on 2025-08-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_queue_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjoblog',
            name='print_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='print_queue_management.printjob'),
        ),
    ]
