# Generated by Django 4.2.23 on 2025-07-07 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_company_company_type'),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('fiscal_year', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('template_type', models.CharField(choices=[('CUSTOM', 'Custom Template'), ('SYSTEM', 'System Template')], default='CUSTOM', max_length=10)),
                ('default_from_date', models.DateField(blank=True, help_text='Default start date', null=True)),
                ('default_to_date', models.DateField(blank=True, help_text='Default end date', null=True)),
                ('default_account_codes', models.TextField(blank=True, help_text='Comma-separated account codes')),
                ('include_sub_accounts', models.BooleanField(default=True)),
                ('include_opening_balance', models.BooleanField(default=True)),
                ('include_closing_balance', models.BooleanField(default=True)),
                ('default_export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Available to all users in the company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name', max_length=200)),
                ('report_type', models.CharField(choices=[('DETAILED', 'Detailed Report'), ('SUMMARY', 'Summary Report'), ('COMPARATIVE', 'Comparative Report')], default='DETAILED', max_length=20)),
                ('from_date', models.DateField(help_text='Start date for the report')),
                ('to_date', models.DateField(help_text='End date for the report')),
                ('include_sub_accounts', models.BooleanField(default=True, help_text='Include sub-accounts in the report')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum transaction amount to include', max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum transaction amount to include', max_digits=15, null=True)),
                ('include_reconciled_only', models.BooleanField(default=False, help_text='Include only reconciled entries')),
                ('include_unreconciled_only', models.BooleanField(default=False, help_text='Include only unreconciled entries')),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', help_text='Default export format', max_length=10)),
                ('include_opening_balance', models.BooleanField(default=True, help_text='Include opening balance in the report')),
                ('include_closing_balance', models.BooleanField(default=True, help_text='Include closing balance in the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False, help_text='Whether this is a saved report')),
                ('last_generated', models.DateTimeField(blank=True, help_text='When the report was last generated', null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Specific account to filter (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_reports', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_ledger_reports_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_reports', to='fiscal_year.fiscalyear')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_ledger_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Ledger Report',
                'verbose_name_plural': 'General Ledger Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
