# Generated by Django 4.2.23 on 2025-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('consignee', 'Consignee'), ('shipper', 'Shipper'), ('agent', 'Agent'), ('broker', 'Broker'), ('vendor', 'Vendor'), ('notify_party', 'Notify Party')], default='customer', max_length=20),
        ),
    ]
