# Generated by Django 4.2.23 on 2025-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_types',
            field=models.ManyToManyField(blank=True, to='customer.customertype'),
        ),
    ]
