# Generated by Django 4.2.23 on 2025-06-20 14:55:49

from django.db import migrations

def create_customer_types(apps, schema_editor):
    CustomerType = apps.get_model('customer', 'CustomerType')
    
    customer_types = [
        {'name': 'Customer', 'code': 'CUS', 'description': 'Regular customer'},
        {'name': 'Consignee', 'code': 'CON', 'description': 'Consignee party'},
        {'name': 'Shipper', 'code': 'SHI', 'description': 'Shipper party'},
        {'name': 'Agent', 'code': 'AGE', 'description': 'Agent or representative'},
        {'name': 'Broker', 'code': 'BRO', 'description': 'Broker or intermediary'},
        {'name': 'Vendor', 'code': 'VEN', 'description': 'Vendor or supplier'},
        {'name': 'Notify Party', 'code': 'NOT', 'description': 'Notify party'},
    ]
    
    for ct_data in customer_types:
        CustomerType.objects.create(**ct_data)

def remove_customer_types(apps, schema_editor):
    CustomerType = apps.get_model('customer', 'CustomerType')
    CustomerType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customertype_remove_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_customer_types, remove_customer_types),
    ]
