# Generated by Django 4.2.23 on 2025-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_populate_customer_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='portal_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
