# Generated by Django 4.2.23 on 2025-06-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_alter_salesman_phone'),
        ('customer', '0005_alter_customer_portal_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='salesman.salesman'),
        ),
    ]
