# Generated by Django 4.2.23 on 2025-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_add_supplier_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
