# Generated by Django 4.2.23 on 2025-08-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_currency', '0001_initial'),
        ('billing_payable_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for this bill amount', null=True, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency'),
        ),
    ]
