# Generated by Django 4.2.23 on 2025-08-29 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing_payable_tracking', '0002_bill_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_days_offset',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days after generation when bill is due', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='generate_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month when bill is generated (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this is a recurring bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='next_generate_date',
            field=models.DateField(blank=True, help_text='Next date when this recurring bill should be generated', null=True),
        ),
        migrations.CreateModel(
            name='BillAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('generated', 'Bill Generated'), ('due_soon', 'Due Soon (4 days before)')], max_length=20)),
                ('show_date', models.DateField(help_text='Date when this alert should be shown')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='billing_payable_tracking.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_dismissed', 'show_date'], name='billing_pay_user_id_0fb2b3_idx'), models.Index(fields=['show_date'], name='billing_pay_show_da_916cde_idx')],
                'unique_together': {('bill', 'user', 'alert_type', 'show_date')},
            },
        ),
    ]
