# Generated by Django 4.2.23 on 2025-08-04 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_item_cbm_item_country_of_origin_item_gross_weight_and_more'),
        ('facility', '0002_facilitylocation'),
        ('grn', '0009_grnpallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='Transfer Number')),
                ('transfer_type', models.CharField(choices=[('internal', 'Internal Transfer'), ('cross_facility', 'Cross Facility Transfer'), ('temporary', 'Temporary Transfer'), ('permanent', 'Permanent Transfer')], default='internal', max_length=20, verbose_name='Transfer Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transfer Date')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_transfers_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='facility.facilitylocation', verbose_name='Destination Location')),
            ],
            options={
                'verbose_name': 'Location Transfer',
                'verbose_name_plural': 'Location Transfers',
                'db_table': 'location_transfer_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_id', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Pallet ID must contain only uppercase letters, numbers, and hyphens.')], verbose_name='Pallet ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='active', max_length=20, verbose_name='Status')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (KGS)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (CBM)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensions (LxWxH)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='facility.facilitylocation', verbose_name='Current Location')),
                ('grn_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grn.grnpallet', verbose_name='Source GRN Pallet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Pallet',
                'verbose_name_plural': 'Pallets',
                'db_table': 'location_transfer_pallet',
                'ordering': ['pallet_id'],
            },
        ),
        migrations.CreateModel(
            name='LocationTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('location_updated', 'Location Updated'), ('notes_updated', 'Notes Updated')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed At')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Additional Data')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='location_transfer.locationtransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Location Transfer History',
                'verbose_name_plural': 'Location Transfer History',
                'db_table': 'location_transfer_history',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_transfer.pallet', verbose_name='Pallet'),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_transfers_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='facility.facilitylocation', verbose_name='Source Location'),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_transfers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.CreateModel(
            name='PalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, verbose_name='Unit of Measure')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Cost')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Value')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_items', to='location_transfer.pallet', verbose_name='Pallet')),
            ],
            options={
                'verbose_name': 'Pallet Item',
                'verbose_name_plural': 'Pallet Items',
                'db_table': 'location_transfer_pallet_item',
                'ordering': ['pallet', 'item'],
                'unique_together': {('pallet', 'item', 'batch_number', 'serial_number')},
            },
        ),
    ]
