# Generated by Django 4.2.23 on 2025-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits package, perks, and additional incentives'),
        ),
    ]
