# Generated by Django 4.2.23 on 2025-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashentry',
            name='job_no',
            field=models.CharField(blank=True, help_text='Job reference number', max_length=50, null=True),
        ),
    ]
