# Generated by Django 4.2.23 on 2025-08-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0002_fix_decimal_defaults'),
        ('petty_cash', '0002_pettycashentry_job_no'),
    ]

    operations = [
    ]
