# Generated by Django 4.2.23 on 2025-07-05 10:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('company', '0003_remove_company_company_type'),
        ('fiscal_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch number', max_length=50, unique=True)),
                ('batch_type', models.CharField(choices=[('JOURNAL', 'Journal Entry'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Balance')], help_text='Type of batch', max_length=20)),
                ('description', models.TextField(help_text='Batch description')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debit amount', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credit amount', max_digits=15)),
                ('is_balanced', models.BooleanField(default=False, help_text='Whether debits equal credits')),
                ('is_posted', models.BooleanField(default=False, help_text='Whether batch has been posted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_batches', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_batches_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_batches', to='fiscal_year.fiscalyear')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_batches_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Batch',
                'verbose_name_plural': 'Ledger Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_number', models.CharField(help_text='Unique ledger entry number', max_length=50, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the ledger entry')),
                ('reference', models.CharField(blank=True, help_text='Reference number or description', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the transaction')),
                ('entry_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], help_text='Debit or Credit entry', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance after this entry', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', help_text='Entry status', max_length=10)),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this entry has been reconciled')),
                ('reconciliation_date', models.DateField(blank=True, help_text='Date when entry was reconciled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Entry creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('voucher_number', models.CharField(blank=True, help_text='Voucher number if applicable', max_length=50)),
                ('cheque_number', models.CharField(blank=True, help_text='Cheque number if applicable', max_length=50)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank reference number', max_length=100)),
                ('account', models.ForeignKey(help_text='Account for this entry', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='chart_of_accounts.chartofaccount')),
                ('company', models.ForeignKey(help_text='Company this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='company.company')),
                ('created_by', models.ForeignKey(help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='Fiscal year for this entry', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='fiscal_year.fiscalyear')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'entry_date'], name='ledger_ledg_account_9217c5_idx'), models.Index(fields=['ledger_number'], name='ledger_ledg_ledger__9d193a_idx'), models.Index(fields=['status'], name='ledger_ledg_status_c22b18_idx'), models.Index(fields=['company', 'fiscal_year'], name='ledger_ledg_company_c70a1a_idx')],
            },
        ),
    ]
