# Generated by Django 4.2.23 on 2025-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount (optional)', max_digits=15, null=True),
        ),
    ]
