# Generated by Django 4.2.23 on 2025-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
