# Generated by Django 4.2.23 on 2025-07-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_salesman'),
        ('supplier_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='customer.customer'),
        ),
    ]
