# Generated by Django 5.0.2 on 2025-08-17 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20250814_1217'),
        ('supplier_payments', '0002_alter_supplierpayment_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='invoice.invoice')),
                ('supplier_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='supplier_payments.supplierpayment')),
            ],
            options={
                'verbose_name': 'Supplier Payment Invoice',
                'verbose_name_plural': 'Supplier Payment Invoices',
                'ordering': ['-created_at'],
                'unique_together': {('supplier_payment', 'invoice')},
            },
        ),
    ]
