# Generated by Django 5.0.2 on 2025-08-17 18:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_bills', '0001_initial'),
        ('supplier_payments', '0003_supplierpaymentinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='supplier_bills.supplierbill')),
                ('supplier_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_bills', to='supplier_payments.supplierpayment')),
            ],
            options={
                'verbose_name': 'Supplier Payment Bill',
                'verbose_name_plural': 'Supplier Payment Bills',
                'ordering': ['-created_at'],
                'unique_together': {('supplier_payment', 'supplier_bill')},
            },
        ),
    ]
