# Generated by Django 4.2.23 on 2025-07-07 15:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('narration', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment_type', models.CharField(choices=[('prepaid_expense', 'Prepaid Expense'), ('accrued_expense', 'Accrued Expense'), ('accrued_income', 'Accrued Income'), ('depreciation', 'Depreciation'), ('reclassification', 'Reclassification'), ('others', 'Others')], default='others', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_entries_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment Entry',
                'verbose_name_plural': 'Adjustment Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.chartofaccount')),
                ('adjustment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='adjustment_entry.adjustmententry')),
            ],
            options={
                'verbose_name': 'Adjustment Entry Detail',
                'verbose_name_plural': 'Adjustment Entry Details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('posted', 'Posted'), ('cancelled', 'Cancelled'), ('entry_added', 'Entry Added'), ('entry_updated', 'Entry Updated'), ('entry_removed', 'Entry Removed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adjustment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='adjustment_entry.adjustmententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment Entry Audit',
                'verbose_name_plural': 'Adjustment Entry Audits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
