# Generated by Django 4.2.23 on 2025-08-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSummaryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('input_output', 'Input/Output Tax Summary'), ('vat_summary', 'VAT Summary'), ('detailed', 'Detailed Tax Report')], default='input_output', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('total_input_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_output_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('input_transactions_count', models.IntegerField(default=0)),
                ('output_transactions_count', models.IntegerField(default=0)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('exported', 'Exported')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tax_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Summary Report',
                'verbose_name_plural': 'Tax Summary Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxSummaryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('transaction_type', models.CharField(choices=[('input', 'Input Tax'), ('output', 'Output Tax')], max_length=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('original_transaction_id', models.CharField(blank=True, max_length=100)),
                ('original_transaction_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax_summary.taxsummaryreport')),
            ],
            options={
                'verbose_name': 'Tax Summary Transaction',
                'verbose_name_plural': 'Tax Summary Transactions',
                'ordering': ['transaction_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='TaxSummaryFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_type', models.CharField(choices=[('date_range', 'Date Range'), ('party_name', 'Party Name'), ('vat_number', 'VAT Number'), ('transaction_type', 'Transaction Type'), ('tax_rate', 'Tax Rate'), ('currency', 'Currency')], max_length=20)),
                ('filter_value', models.CharField(max_length=255)),
                ('filter_label', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='tax_summary.taxsummaryreport')),
            ],
            options={
                'verbose_name': 'Tax Summary Filter',
                'verbose_name_plural': 'Tax Summary Filters',
            },
        ),
        migrations.CreateModel(
            name='TaxSummaryExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_tax_summaries', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='tax_summary.taxsummaryreport')),
            ],
            options={
                'verbose_name': 'Tax Summary Export',
                'verbose_name_plural': 'Tax Summary Exports',
                'ordering': ['-exported_at'],
            },
        ),
    ]
