# Generated by Django 5.0.2 on 2025-08-09 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('approval_type', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('hybrid', 'Hybrid')], default='sequential', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_type', models.CharField(blank=True, choices=[('amount', 'Amount Threshold'), ('department', 'Department'), ('cost_center', 'Cost Center'), ('project', 'Project'), ('role', 'Role'), ('user', 'Specific User')], max_length=20)),
                ('condition_value', models.CharField(blank=True, help_text='JSON or specific value', max_length=500)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approval_levels', models.PositiveIntegerField(default=1)),
                ('auto_approve_if_no_approvers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('auto_approval_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Amount threshold for auto-approval', max_digits=15)),
                ('max_approval_days', models.PositiveIntegerField(default=7, help_text='Maximum days for approval before escalation')),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending Approval'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_id', models.CharField(blank=True, max_length=100)),
                ('document_reference', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('current_approvers', models.ManyToManyField(blank=True, related_name='current_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='approval_workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_submitted', 'Request Submitted'), ('approval_required', 'Approval Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('overdue', 'Overdue'), ('reminder', 'Reminder')], max_length=20)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-App'), ('push', 'Push Notification')], default='in_app', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_notifications', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='approval_workflow.approvalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_comments', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='approval_workflow.approvalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('assigned', 'Assigned'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('commented', 'Commented'), ('notified', 'Notified')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='approval_workflow.approvalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('level_type', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('approver_roles', models.CharField(blank=True, help_text='Comma-separated role names', max_length=500)),
                ('min_approvals_required', models.PositiveIntegerField(default=1)),
                ('deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours before escalation')),
                ('can_approve', models.BooleanField(default=True)),
                ('can_reject', models.BooleanField(default=True)),
                ('can_return', models.BooleanField(default=True)),
                ('can_comment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_groups', models.ManyToManyField(blank=True, related_name='workflow_levels', to='auth.group')),
                ('approvers', models.ManyToManyField(blank=True, related_name='workflow_levels', to=settings.AUTH_USER_MODEL)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='approval_workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow_definition', 'level_number'],
                'unique_together': {('workflow_definition', 'level_number')},
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_workflow.workflowlevel'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='approval_workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='approval_workflow.workflowtype'),
        ),
        migrations.CreateModel(
            name='WorkflowLevelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_level_approvals', to='approval_workflow.approvalrequest')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_approvals', to=settings.AUTH_USER_MODEL)),
                ('workflow_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='approval_workflow.workflowlevel')),
            ],
            options={
                'ordering': ['workflow_level__level_number', '-assigned_at'],
                'unique_together': {('approval_request', 'workflow_level', 'approver')},
            },
        ),
    ]
