# Generated by Django 4.2.23 on 2025-07-08 15:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Name for this reconciliation session', max_length=200)),
                ('reconciliation_date', models.DateField(help_text='Date of reconciliation')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked')], default='open', max_length=20)),
                ('tolerance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Tolerance amount for partial matches', max_digits=15)),
                ('opening_balance_erp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance_erp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_erp_credits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_erp_debits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bank_credits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bank_debits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='bank_accounts.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliation_sessions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reconciliation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation Session',
                'verbose_name_plural': 'Bank Reconciliation Sessions',
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('import_source', models.CharField(default='manual', help_text='Source of import (manual, csv, excel)', max_length=50)),
                ('import_reference', models.CharField(blank=True, help_text='Reference from import file', max_length=200, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('match_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Statement Entry',
                'verbose_name_plural': 'Bank Statement Entries',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_matched', models.BooleanField(default=False)),
                ('match_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='chart_of_accounts.chartofaccount')),
                ('matched_bank_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_erp_entries', to='bank_reconciliation.bankstatemententry')),
                ('reconciliation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_entries', to='bank_reconciliation.bankreconciliationsession')),
            ],
            options={
                'verbose_name': 'ERP Transaction',
                'verbose_name_plural': 'ERP Transactions',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('unmatched', 'Unmatched Entries Report'), ('reconciliation_statement', 'Reconciliation Statement')], max_length=30)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(default=dict, help_text='Structured report data')),
                ('report_file', models.FileField(blank=True, help_text='Generated report file (PDF/Excel)', null=True, upload_to='reconciliation_reports/')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciliation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bank_reconciliation.bankreconciliationsession')),
            ],
            options={
                'verbose_name': 'Reconciliation Report',
                'verbose_name_plural': 'Reconciliation Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddField(
            model_name='bankstatemententry',
            name='matched_erp_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_entries', to='bank_reconciliation.erptransaction'),
        ),
        migrations.AddField(
            model_name='bankstatemententry',
            name='reconciliation_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_entries', to='bank_reconciliation.bankreconciliationsession'),
        ),
        migrations.CreateModel(
            name='MatchedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match'), ('manual', 'Manual Match')], default='manual', max_length=20)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=100.0, help_text='Confidence score of the match (0-100)', max_digits=5)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, help_text='Difference between ERP and Bank amounts', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliation.bankstatemententry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('erp_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliation.erptransaction')),
                ('reconciliation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_entries', to='bank_reconciliation.bankreconciliationsession')),
            ],
            options={
                'verbose_name': 'Matched Entry',
                'verbose_name_plural': 'Matched Entries',
                'ordering': ['-created_at'],
                'unique_together': {('erp_entry', 'bank_entry')},
            },
        ),
    ]
