# Generated by Django 4.2.23 on 2025-08-09 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost_center_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterFinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('summary', 'Summary View'), ('detailed', 'Detailed View'), ('budget_variance', 'Budget Variance'), ('profit_loss', 'Profit & Loss'), ('expense_analysis', 'Expense Analysis')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('include_inactive', models.BooleanField(default=False, help_text='Include inactive cost centers in the report')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('report_data', models.JSONField(default=dict, help_text='Stored report data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='cost_center_management.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='cost_center_management.department')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cost_center_financial_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Center Financial Report',
                'verbose_name_plural': 'Cost Center Financial Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('summary', 'Summary View'), ('detailed', 'Detailed View'), ('budget_variance', 'Budget Variance'), ('profit_loss', 'Profit & Loss'), ('expense_analysis', 'Expense Analysis')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to receive the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_center_report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Center Report Schedule',
                'verbose_name_plural': 'Cost Center Report Schedules',
                'ordering': ['schedule_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterReportFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_name', models.CharField(max_length=100)),
                ('filter_value', models.TextField()),
                ('filter_type', models.CharField(help_text='Type of filter (date_range, cost_center, department, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='cost_center_reports.costcenterfinancialreport')),
            ],
            options={
                'verbose_name': 'Cost Center Report Filter',
                'verbose_name_plural': 'Cost Center Report Filters',
                'ordering': ['filter_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cost_center_report_exports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cost_center_reports.costcenterfinancialreport')),
            ],
            options={
                'verbose_name': 'Cost Center Report Export',
                'verbose_name_plural': 'Cost Center Report Exports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
