# Generated by Django 5.0.2 on 2025-08-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0007_add_supplier_customer_type'),
        ('facility', '0002_facilitylocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgp_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dpw_ref_no', models.CharField(max_length=100, verbose_name='DPW Ref No')),
                ('document_date', models.DateField()),
                ('document_validity_date', models.DateField()),
                ('free_zone_company_name', models.CharField(max_length=200)),
                ('local_company_name', models.CharField(max_length=200)),
                ('goods_coming_from', models.CharField(max_length=200)),
                ('purpose_of_entry', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lgps', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgps', to='customer.customer')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_lgps', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgps', to='facility.facility')),
            ],
            options={
                'verbose_name': 'LGP',
                'verbose_name_plural': 'LGPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LGPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=20, verbose_name='HS Code')),
                ('good_description', models.TextField(verbose_name='Good Description')),
                ('marks_and_nos', models.CharField(max_length=200, verbose_name='Marks & Nos')),
                ('package_type', models.CharField(choices=[('box', 'Box'), ('carton', 'Carton'), ('pallet', 'Pallet'), ('bag', 'Bag'), ('drum', 'Drum'), ('container', 'Container'), ('bundle', 'Bundle'), ('roll', 'Roll'), ('piece', 'Piece'), ('other', 'Other')], max_length=20, verbose_name='Package Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in KG', max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, help_text='Volume in CBM', max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Value in currency', max_digits=15)),
                ('customs_declaration', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('lgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lgp.lgp')),
            ],
            options={
                'verbose_name': 'LGP Item',
                'verbose_name_plural': 'LGP Items',
                'ordering': ['line_number'],
            },
        ),
    ]
