# Generated by Django 4.2.23 on 2025-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgp',
            name='purpose_of_entry',
            field=models.CharField(choices=[('storage', 'Storage'), ('office_user', 'Office User'), ('export', 'Export')], max_length=20),
        ),
    ]
