# Generated by Django 4.2.23 on 2025-08-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0008_alter_customer_customer_code'),
        ('lgp', '0002_alter_lgp_purpose_of_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGPDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lgp_dispatches', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgp_dispatches', to='customer.customer')),
            ],
            options={
                'verbose_name': 'LGP Dispatch',
                'verbose_name_plural': 'LGP Dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LGPDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('hs_code', models.CharField(max_length=20)),
                ('good_description', models.TextField()),
                ('package_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lgp.lgpdispatch')),
                ('lgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_items', to='lgp.lgp')),
                ('lgp_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_rows', to='lgp.lgpitem')),
            ],
            options={
                'verbose_name': 'LGP Dispatch Item',
                'verbose_name_plural': 'LGP Dispatch Items',
                'ordering': ['dispatch_id', 'line_number'],
            },
        ),
    ]
