# Generated by Django 4.2.23 on 2025-08-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgp', '0003_lgpdispatch_lgpdispatchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Package Type Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Package Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Type',
                'verbose_name_plural': 'Package Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lgpitem',
            name='package_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('carton', 'Carton'), ('pallet', 'Pallet'), ('bag', 'Bag'), ('drum', 'Drum'), ('container', 'Container'), ('bundle', 'Bundle'), ('roll', 'Roll'), ('piece', 'Piece'), ('other', 'Other')], max_length=20, verbose_name='Package Type (Legacy)'),
        ),
        migrations.AddField(
            model_name='lgpitem',
            name='package_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lgp.packagetype', verbose_name='Package Type'),
        ),
    ]
