# Generated by Django 4.2.23 on 2025-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgp', '0004_packagetype_alter_lgpitem_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpitem',
            name='marks_and_nos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marks & Nos'),
        ),
        migrations.AlterField(
            model_name='lgpitem',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume in CBM', max_digits=10, null=True),
        ),
    ]
