# Generated by Django 4.2.23 on 2025-08-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_company_logo'),
        ('customer', '0008_alter_customer_customer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiscal_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLedgerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text='Name for this report configuration', max_length=100)),
                ('date_from', models.DateField(help_text='Start date for the report')),
                ('date_to', models.DateField(help_text='End date for the report')),
                ('payment_status', models.CharField(choices=[('all', 'All'), ('pending', 'Pending'), ('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid')], default='all', help_text='Payment status filter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_ledger_reports_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal_year.fiscalyear')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_ledger_reports_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Specific vendor (leave blank for all vendors)', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'Vendor Ledger Report',
                'verbose_name_plural': 'Vendor Ledger Reports',
                'db_table': 'vendor_ledger_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
