# Generated by Django 4.2.23 on 2025-07-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispose_asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposalrequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_disposal', 'Can approve disposal requests'), ('can_dispose_asset', 'Can execute asset disposal'), ('can_reverse_disposal', 'Can reverse disposal'), ('can_edit_disposal', 'Can edit disposal requests')]},
        ),
    ]
