# Generated by Django 4.2.23 on 2025-07-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fiscal_year_start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Default month for fiscal year start')),
                ('default_period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', help_text='Default period type for new fiscal years', max_length=20)),
                ('auto_create_periods', models.BooleanField(default=True, help_text='Automatically create periods when creating a new fiscal year')),
                ('allow_overlapping_periods', models.BooleanField(default=False, help_text='Allow overlapping periods within the same fiscal year')),
                ('require_period_approval', models.BooleanField(default=False, help_text='Require approval before closing periods')),
                ('fiscal_year_naming_convention', models.CharField(default='FY {start_year}-{end_year}', help_text='Naming convention for fiscal years (use {start_year} and {end_year} placeholders)', max_length=100)),
                ('period_naming_convention', models.CharField(default='{period_type} {period_number}', help_text='Naming convention for periods (use {period_type} and {period_number} placeholders)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Settings',
                'verbose_name_plural': 'Fiscal Settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fiscal year name (e.g., FY 2024-25)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of the fiscal year')),
                ('end_date', models.DateField(help_text='End date of the fiscal year')),
                ('is_current', models.BooleanField(default=False, help_text='Mark as current fiscal year')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='inactive', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Period name (e.g., Q1, January)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of the period')),
                ('end_date', models.DateField(help_text='End date of the period')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='Mark as current period')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='fiscal_year.fiscalyear')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['fiscal_year', 'start_date'],
                'unique_together': {('fiscal_year', 'name')},
            },
        ),
    ]
