# Generated by Django 4.2.23 on 2025-07-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('journal_entry', 'Journal Entry'), ('contra_entry', 'Contra Entry'), ('adjustment_entry', 'Adjustment Entry'), ('opening_balance', 'Opening Balance')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('draft', 'Draft'), ('reversed', 'Reversed')], default='posted', max_length=10)),
                ('source_model', models.CharField(max_length=50)),
                ('source_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='chart_of_accounts.chartofaccount')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='chart_of_accounts.chartofaccount')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'all_transactions_view',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='all_transac_transac_697593_idx'), models.Index(fields=['transaction_type'], name='all_transac_transac_ef4d2a_idx'), models.Index(fields=['status'], name='all_transac_status_9d7195_idx'), models.Index(fields=['posted_by'], name='all_transac_posted__1e7f03_idx'), models.Index(fields=['debit_account'], name='all_transac_debit_a_f040ef_idx'), models.Index(fields=['credit_account'], name='all_transac_credit__5e2396_idx'), models.Index(fields=['source_model', 'source_id'], name='all_transac_source__a41e02_idx')],
            },
        ),
    ]
