# Generated by Django 4.2.23 on 2025-07-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('POST', 'Posted'), ('CANCEL', 'Cancelled'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20)),
                ('description', models.TextField()),
                ('model_name', models.CharField(help_text='Name of the model being acted upon', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object being acted upon', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_a_created_fb7b78_idx'), models.Index(fields=['user', 'created_at'], name='dashboard_a_user_id_caeacd_idx'), models.Index(fields=['activity_type', 'created_at'], name='dashboard_a_activit_333425_idx'), models.Index(fields=['model_name', 'created_at'], name='dashboard_a_model_n_7d6f97_idx')],
            },
        ),
    ]
