# Generated by Django 4.2.23 on 2025-07-09 08:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('multi_currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=20)),
                ('category', models.CharField(choices=[('petty_expense', 'Petty Expense'), ('cash_sale', 'Cash Sale'), ('staff_advance', 'Staff Advance'), ('reimbursement', 'Reimbursement'), ('cash_purchase', 'Cash Purchase'), ('cash_receipt', 'Cash Receipt'), ('cash_payment', 'Cash Payment'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location', models.CharField(blank=True, help_text='Branch or location', max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cash_transactions/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_from', to='chart_of_accounts.chartofaccount')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_posted', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_to', to='chart_of_accounts.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='cash_transactions.cashtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction Audit',
                'verbose_name_plural': 'Cash Transaction Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency')),
            ],
            options={
                'verbose_name': 'Cash Balance',
                'verbose_name_plural': 'Cash Balances',
                'unique_together': {('location', 'currency')},
            },
        ),
    ]
