# Generated by Django 4.2.23 on 2025-08-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this notification is active'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='name',
            field=models.CharField(default='Notification', help_text='Descriptive name for this notification', max_length=100),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='recipient_email',
            field=models.EmailField(default='admin@example.com', help_text='Primary recipient email address', max_length=254),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='email_configuration.emailconfiguration'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.JSONField(default=list, help_text='List of recipient email addresses'),
        ),
    ]
