# Generated by Django 4.2.23 on 2025-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='partial_payment_option',
            field=models.CharField(blank=True, choices=[('keep_open', 'Keep Invoice Open'), ('discount', 'Apply Discount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpaymentinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerpaymentinvoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
