# Generated by Django 5.0.2 on 2025-08-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('customer_payments', '0002_customerpayment_partial_payment_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Select bank account for bank transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.bankaccount'),
        ),
    ]
