# Generated by Django 4.2.23 on 2025-08-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('customer_payments', '0003_customerpayment_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='ledger_account',
            field=models.ForeignKey(blank=True, help_text='Select ledger account for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart_of_accounts.chartofaccount'),
        ),
    ]
