# Generated by Django 5.0.2 on 2025-08-17 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the cron job', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this job does')),
                ('task', models.CharField(help_text='Celery task name to execute', max_length=200)),
                ('schedule', models.CharField(help_text="Cron expression (e.g., '0 0 * * *') or interval (e.g., '5 minutes')", max_length=100)),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron Expression'), ('interval', 'Interval')], default='cron', help_text='Type of schedule', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job is currently active')),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last execution time', null=True)),
                ('last_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this cron job', on_delete=django.db.models.deletion.CASCADE, related_name='owned_cron_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cron Job',
                'verbose_name_plural': 'Cron Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_started_at', models.DateTimeField(auto_now_add=True)),
                ('run_ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('output_message', models.TextField(blank=True, help_text='Task output or error message')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('worker_name', models.CharField(blank=True, help_text='Name of the worker that executed the task', max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='cron_job_viewer.cronjob')),
            ],
            options={
                'verbose_name': 'Cron Job Log',
                'verbose_name_plural': 'Cron Job Logs',
                'ordering': ['-run_started_at'],
            },
        ),
    ]
