# Generated by Django 4.2.23 on 2025-08-09 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_register', '0001_initial'),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('general_journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_post_to_gl', models.BooleanField(default=False, help_text='Automatically post to general ledger')),
                ('require_approval', models.BooleanField(default=True, help_text='Require approval before posting')),
                ('minimum_depreciation_amount', models.DecimalField(decimal_places=2, default=0.01, help_text='Minimum depreciation amount to post', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_depreciation_settings', to=settings.AUTH_USER_MODEL)),
                ('default_accumulated_depreciation_account', models.ForeignKey(blank=True, help_text='Default account for accumulated depreciation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accumulated_depreciation_settings', to='chart_of_accounts.chartofaccount')),
                ('default_depreciation_expense_account', models.ForeignKey(blank=True, help_text='Default account for depreciation expense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_depreciation_expense_settings', to='chart_of_accounts.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_depreciation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depreciation Setting',
                'verbose_name_plural': 'Depreciation Settings',
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_assets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='Account to credit for accumulated depreciation', on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_schedules', to='chart_of_accounts.chartofaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_depreciation_schedules', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(help_text='Account to debit for depreciation expense', on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_schedules', to='chart_of_accounts.chartofaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_schedules', to='general_journal.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_depreciation_schedules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_depreciation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depreciation Schedule',
                'verbose_name_plural': 'Depreciation Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Period (YYYY-MM-01)')),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='asset_register.asset')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='depreciation_schedule.depreciationschedule')),
            ],
            options={
                'verbose_name': 'Depreciation Entry',
                'verbose_name_plural': 'Depreciation Entries',
                'ordering': ['asset__asset_code', 'period'],
                'unique_together': {('schedule', 'asset', 'period')},
            },
        ),
    ]
