# Generated by Django 4.2.23 on 2025-06-20 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Unique item code (e.g., ITM-001, PROD-002)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Item code must contain only uppercase letters, numbers, and hyphens.')])),
                ('item_name', models.CharField(help_text='Full name of the item', max_length=200)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('material', 'Material'), ('equipment', 'Equipment'), ('consumable', 'Consumable')], default='product', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for display', max_length=500)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg', max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='PCS', help_text='Unit of measurement (PCS, KG, L, etc.)', max_length=20)),
                ('min_stock_level', models.PositiveIntegerField(default=0, help_text='Minimum stock level for reorder')),
                ('max_stock_level', models.PositiveIntegerField(default=0, help_text='Maximum stock level')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='Stock level at which to reorder')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit', max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('supplier', models.CharField(blank=True, help_text='Primary supplier name', max_length=200)),
                ('supplier_code', models.CharField(blank=True, help_text="Supplier's item code", max_length=50)),
                ('lead_time', models.PositiveIntegerField(default=0, help_text='Lead time in days')),
                ('warehouse_location', models.CharField(blank=True, help_text='Storage location in warehouse', max_length=100)),
                ('shelf_number', models.CharField(blank=True, max_length=20)),
                ('bin_number', models.CharField(blank=True, max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Barcode or SKU', max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number if applicable', max_length=100)),
                ('warranty_period', models.PositiveIntegerField(default=0, help_text='Warranty period in months')),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
                'ordering': ['item_name'],
            },
        ),
    ]
