# Generated by Django 4.2.23 on 2025-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('toiletries', 'Toiletries'), ('food_beverages', 'Food & Beverages'), ('dairy_products', 'Dairy Products'), ('frozen_food', 'Frozen Food'), ('bakery_items', 'Bakery Items'), ('snacks', 'Snacks'), ('meat_seafood', 'Meat & Seafood'), ('fruits_vegetables', 'Fruits & Vegetables'), ('spices_condiments', 'Spices & Condiments'), ('cooking_essentials', 'Cooking Essentials'), ('automobile', 'Automobile'), ('car_accessories', 'Car Accessories'), ('bike_accessories', 'Bike Accessories'), ('tyres_tubes', 'Tyres & Tubes'), ('lubricants', 'Lubricants'), ('electronics', 'Electronics'), ('mobile_phones', 'Mobile Phones'), ('televisions', 'Televisions'), ('cameras', 'Cameras'), ('audio_devices', 'Audio Devices'), ('computers_parts', 'Computers & Parts'), ('laptops', 'Laptops'), ('desktops', 'Desktops'), ('keyboards_mice', 'Keyboards & Mice'), ('monitors', 'Monitors'), ('storage_devices', 'Storage Devices'), ('printers_scanners', 'Printers & Scanners'), ('household_items', 'Household Items'), ('furniture', 'Furniture'), ('lighting', 'Lighting'), ('kitchenware', 'Kitchenware'), ('storage_containers', 'Storage & Containers'), ('cleaning_supplies', 'Cleaning Supplies'), ('kitchen_appliances', 'Kitchen Appliances'), ('home_decor', 'Home Decor'), ('curtains_carpets', 'Curtains & Carpets'), ('office_supplies', 'Office Supplies'), ('stationery', 'Stationery'), ('paper_products', 'Paper Products'), ('files_folders', 'Files & Folders'), ('beauty_personal_care', 'Beauty & Personal Care'), ('skin_care', 'Skin Care'), ('hair_care', 'Hair Care'), ('oral_care', 'Oral Care'), ('perfumes_deodorants', 'Perfumes & Deodorants'), ('health_wellness', 'Health & Wellness'), ('medicines', 'Medicines'), ('first_aid', 'First Aid'), ('supplements', 'Supplements'), ('fitness_equipment', 'Fitness Equipment'), ('baby_products', 'Baby Products'), ('diapers', 'Diapers'), ('baby_food', 'Baby Food'), ('baby_toiletries', 'Baby Toiletries'), ('toys_games', 'Toys & Games'), ('clothing_apparel', 'Clothing & Apparel'), ('mens_clothing', "Men's Clothing"), ('womens_clothing', "Women's Clothing"), ('kids_clothing', "Kids' Clothing"), ('footwear', 'Footwear'), ('bags_luggage', 'Bags & Luggage'), ('sports_outdoor', 'Sports & Outdoor'), ('garden_supplies', 'Garden Supplies'), ('pet_supplies', 'Pet Supplies'), ('books_magazines', 'Books & Magazines'), ('construction_materials', 'Construction Materials'), ('electrical_supplies', 'Electrical Supplies'), ('plumbing_materials', 'Plumbing Materials'), ('tools_hardware', 'Tools & Hardware'), ('paint_accessories', 'Paint & Accessories'), ('safety_equipment', 'Safety Equipment'), ('packaging_materials', 'Packaging Materials'), ('travel_accessories', 'Travel Accessories'), ('party_supplies', 'Party Supplies')], default='household_items', max_length=50),
        ),
    ]
