# Generated by Django 4.2.23 on 2025-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_type_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic Meter (CBM)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Country of Origin', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Gross Weight (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hs_code',
            field=models.CharField(blank=True, help_text='HS Code', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net Weight (kg)', max_digits=10, null=True),
        ),
    ]
