# Generated by Django 4.2.23 on 2025-06-20 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('freight', 'Freight'), ('customs', 'Customs Clearance'), ('warehousing', 'Warehousing'), ('transportation', 'Transportation'), ('packaging', 'Packaging'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(choices=[('AED', 'AED (UAE Dirham)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('SAR', 'SAR (Saudi Riyal)'), ('INR', 'INR (Indian Rupee)')], default='AED', max_length=3)),
                ('pricing_model', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
    ]
