# Generated by Django 4.2.23 on 2025-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_vat',
            field=models.BooleanField(default=True, verbose_name='Has VAT'),
        ),
    ]
