# Generated by Django 4.2.23 on 2025-07-03 11:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, AED)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full currency name (e.g., US Dollar, Euro, UAE Dirham)', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, د.إ)', max_length=10)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Mark as base currency for the system')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is active for transactions')),
                ('decimal_places', models.PositiveIntegerField(default=2, help_text='Number of decimal places for this currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_rates', models.BooleanField(default=False, help_text='Automatically update exchange rates from API')),
                ('api_provider', models.CharField(blank=True, help_text='API provider for exchange rates (e.g., exchangerate-api.com)', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='API key for exchange rate service', max_length=255)),
                ('update_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to update exchange rates', max_length=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, help_text='Default currency for the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='multi_currency.currency')),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (1 from_currency = rate to_currency)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('rate_type', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('auto', 'Auto')], default='manual', help_text='How this rate was obtained', max_length=10)),
                ('effective_date', models.DateField(help_text='Date when this rate becomes effective')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when this rate expires (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(help_text='Source currency', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='multi_currency.currency')),
                ('to_currency', models.ForeignKey(help_text='Target currency', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='multi_currency.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date', 'from_currency', 'to_currency'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
