# Generated by Django 4.2.23 on 2025-06-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_salesman'),
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='bill_to',
            field=models.CharField(blank=True, help_text='Bill to party', max_length=200),
        ),
        migrations.AddField(
            model_name='documentation',
            name='bill_to_address',
            field=models.TextField(blank=True, help_text='Bill to address'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='boe',
            field=models.CharField(blank=True, help_text='Bill of Entry number', max_length=50),
        ),
        migrations.AddField(
            model_name='documentation',
            name='container',
            field=models.CharField(blank=True, help_text='Container number', max_length=50),
        ),
        migrations.AddField(
            model_name='documentation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='date',
            field=models.DateField(blank=True, help_text='Document date', null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='deliver_to_address',
            field=models.TextField(blank=True, help_text='Delivery address'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='delivery_terms',
            field=models.CharField(blank=True, help_text='Delivery terms', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='destination',
            field=models.CharField(blank=True, help_text='Final destination', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='discharge_port',
            field=models.CharField(blank=True, help_text='Port of discharge', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='document_no',
            field=models.CharField(blank=True, help_text='Document number', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='document_type',
            field=models.CharField(blank=True, help_text='Type of document', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='exit_point',
            field=models.CharField(blank=True, help_text='Exit point', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='payment_mode',
            field=models.CharField(blank=True, help_text='Payment mode', max_length=50),
        ),
        migrations.AddField(
            model_name='documentation',
            name='port_of_loading',
            field=models.CharField(blank=True, help_text='Port of loading', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='ship_date',
            field=models.DateField(blank=True, help_text='Ship date', null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='ship_mode',
            field=models.CharField(blank=True, help_text='Shipping mode', max_length=50),
        ),
        migrations.AddField(
            model_name='documentation',
            name='vessel',
            field=models.CharField(blank=True, help_text='Vessel name', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='voyage',
            field=models.CharField(blank=True, help_text='Voyage number', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
