# Generated by Django 4.2.23 on 2025-06-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_documentation_bill_to_documentation_bill_to_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='title',
        ),
    ]
