# Generated by Django 4.2.23 on 2025-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_remove_title_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('TOO', 'Transit out'), ('IMPORT', 'Import to local from FZ')], help_text='Type of document', max_length=20),
        ),
    ]
