# Generated by Django 4.2.23 on 2025-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_add_document_type_choices_and_auto_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('TOO', 'TOO'), ('TRANSIT_OUT', 'Transit Out'), ('IMPORT_LOCAL', 'Import to local from FZ')], help_text='Type of document', max_length=20),
        ),
    ]
