# Generated by Django 4.2.23 on 2025-06-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_update_document_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TT', 'Bank TT'), ('CREDIT', 'Credit')], help_text='Payment mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='ship_mode',
            field=models.CharField(blank=True, choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], help_text='Shipping mode', max_length=20),
        ),
    ]
