# Generated by Django 4.2.23 on 2025-06-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
        ('documentation', '0006_add_payment_ship_mode_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='discharge_port',
            field=models.ForeignKey(blank=True, help_text='Port of discharge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_documentations', to='port.port'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='exit_point',
            field=models.ForeignKey(blank=True, help_text='Exit point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_documentations', to='port.port'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='port_of_loading',
            field=models.ForeignKey(blank=True, help_text='Port of loading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_documentations', to='port.port'),
        ),
    ]
