# Generated by Django 4.2.23 on 2025-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_add_port_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='destination',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('IN', 'India'), ('US', 'United States'), ('CN', 'China'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('SG', 'Singapore'), ('JP', 'Japan'), ('AU', 'Australia'), ('CA', 'Canada'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('KR', 'South Korea'), ('RU', 'Russia'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('ZA', 'South Africa'), ('TH', 'Thailand'), ('MY', 'Malaysia'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('LK', 'Sri Lanka'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('MA', 'Morocco'), ('TN', 'Tunisia'), ('DZ', 'Algeria'), ('LB', 'Lebanon'), ('JO', 'Jordan'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('BH', 'Bahrain'), ('OM', 'Oman'), ('YE', 'Yemen'), ('IQ', 'Iraq'), ('IR', 'Iran'), ('AF', 'Afghanistan'), ('UZ', 'Uzbekistan'), ('KZ', 'Kazakhstan'), ('KG', 'Kyrgyzstan'), ('TJ', 'Tajikistan'), ('TM', 'Turkmenistan'), ('AZ', 'Azerbaijan'), ('GE', 'Georgia'), ('AM', 'Armenia'), ('CY', 'Cyprus'), ('MT', 'Malta'), ('GR', 'Greece'), ('PT', 'Portugal'), ('IE', 'Ireland'), ('BE', 'Belgium'), ('AT', 'Austria'), ('CH', 'Switzerland'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('HR', 'Croatia'), ('SI', 'Slovenia'), ('SK', 'Slovakia'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('LU', 'Luxembourg'), ('IS', 'Iceland'), ('NZ', 'New Zealand'), ('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Peru'), ('CO', 'Colombia'), ('VE', 'Venezuela'), ('EC', 'Ecuador'), ('UY', 'Uruguay'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('GY', 'Guyana'), ('SR', 'Suriname'), ('GF', 'French Guiana'), ('FK', 'Falkland Islands'), ('GS', 'South Georgia'), ('AI', 'Anguilla'), ('AG', 'Antigua and Barbuda'), ('AW', 'Aruba'), ('BS', 'Bahamas'), ('BB', 'Barbados'), ('BZ', 'Belize'), ('BM', 'Bermuda'), ('VG', 'British Virgin Islands'), ('KY', 'Cayman Islands'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('SV', 'El Salvador'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GT', 'Guatemala'), ('HT', 'Haiti'), ('HN', 'Honduras'), ('JM', 'Jamaica'), ('MQ', 'Martinique'), ('MS', 'Montserrat'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('PR', 'Puerto Rico'), ('BL', 'Saint Barthélemy'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('TT', 'Trinidad and Tobago'), ('TC', 'Turks and Caicos Islands'), ('VI', 'U.S. Virgin Islands')], help_text='Final destination country', max_length=3),
        ),
    ]
