# Generated by Django 4.2.23 on 2025-06-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobcontainer'),
        ('documentation', '0008_add_destination_country_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='bl_number',
            field=models.CharField(blank=True, help_text='Bill of Lading number', max_length=100),
        ),
        migrations.AddField(
            model_name='documentation',
            name='job_no',
            field=models.CharField(blank=True, help_text='Job number', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentationCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coo', models.CharField(blank=True, max_length=100)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='documentation.documentation')),
                ('job_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_items', to='job.jobcargo')),
            ],
            options={
                'verbose_name': 'Documentation Cargo',
                'verbose_name_plural': 'Documentation Cargo',
                'ordering': ['created_at'],
            },
        ),
    ]
