# Generated by Django 5.0.2 on 2025-08-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_add_supplier_customer_type'),
        ('documentation', '0009_documentation_bl_number_documentation_job_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='deliver_to',
            field=models.ForeignKey(blank=True, help_text='Customer for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documentations', to='customer.customer'),
        ),
    ]
