# Generated by Django 4.2.23 on 2025-08-06 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clearance Department',
                'verbose_name_plural': 'Clearance Departments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_items', to='exit_management.clearancedepartment')),
            ],
            options={
                'verbose_name': 'Clearance Item',
                'verbose_name_plural': 'Clearance Items',
                'ordering': ['department__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExitConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exit Configuration',
                'verbose_name_plural': 'Exit Configurations',
            },
        ),
        migrations.CreateModel(
            name='ExitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exit Type',
                'verbose_name_plural': 'Exit Types',
            },
        ),
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('contract_type', models.CharField(choices=[('limited', 'Limited Contract'), ('unlimited', 'Unlimited Contract')], default='unlimited', max_length=20)),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('notice_period_served', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_review', 'Manager Review'), ('hr_approval', 'HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('exit_processing', 'Exit Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_step', models.CharField(default='resignation_submitted', max_length=50)),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_approval_date', models.DateTimeField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resignation_letter', models.FileField(blank=True, null=True, upload_to='exit_management/resignation_letters/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_requests', to='employees.employee')),
                ('exit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit_management.exittype')),
                ('hr_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_resignations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_resignations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resignation Request',
                'verbose_name_plural': 'Resignation Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GratuityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_years_service', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract_type', models.CharField(choices=[('limited', 'Limited Contract'), ('unlimited', 'Unlimited Contract')], max_length=20)),
                ('first_five_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('after_five_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_rate_21_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_rate_30_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gratuity_first_five', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_after_five', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_period_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity_calculation', to='exit_management.resignationrequest')),
            ],
            options={
                'verbose_name': 'Gratuity Calculation',
                'verbose_name_plural': 'Gratuity Calculations',
            },
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_month_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_period_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_statement', models.FileField(blank=True, null=True, upload_to='exit_management/settlements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='exit_management.resignationrequest')),
            ],
            options={
                'verbose_name': 'Final Settlement',
                'verbose_name_plural': 'Final Settlements',
            },
        ),
        migrations.CreateModel(
            name='ExitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resignation_acceptance', 'Resignation Acceptance Letter'), ('experience_letter', 'Experience Letter'), ('settlement_statement', 'Final Settlement Statement'), ('clearance_certificate', 'Clearance Certificate'), ('noc_letter', 'NOC Letter')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='exit_management/documents/')),
                ('is_bilingual', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_documents', to='exit_management.resignationrequest')),
            ],
            options={
                'verbose_name': 'Exit Document',
                'verbose_name_plural': 'Exit Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('resignation_submitted', 'Resignation Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('clearance_started', 'Clearance Started'), ('clearance_completed', 'Clearance Completed'), ('gratuity_calculated', 'Gratuity Calculated'), ('settlement_processed', 'Settlement Processed'), ('document_generated', 'Document Generated'), ('exit_completed', 'Exit Completed')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='exit_management.resignationrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit Audit Log',
                'verbose_name_plural': 'Exit Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resignation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_process', to='exit_management.resignationrequest')),
            ],
            options={
                'verbose_name': 'Clearance Process',
                'verbose_name_plural': 'Clearance Processes',
            },
        ),
        migrations.CreateModel(
            name='ClearanceItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('not_applicable', 'Not Applicable'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit_management.clearanceitem')),
                ('clearance_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_items', to='exit_management.clearanceprocess')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clearance Item Status',
                'verbose_name_plural': 'Clearance Item Statuses',
                'unique_together': {('clearance_process', 'clearance_item')},
            },
        ),
    ]
