# Generated by Django 4.2.23 on 2025-08-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this gateway', max_length=100)),
                ('gateway_type', models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo/Vonage'), ('aws_sns', 'AWS SNS'), ('infobip', 'Infobip'), ('messagebird', 'MessageBird'), ('custom', 'Custom API')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gateway is active')),
                ('api_key', models.CharField(help_text='API key or access token', max_length=255)),
                ('api_secret', models.CharField(help_text='API secret or password', max_length=255)),
                ('username', models.CharField(blank=True, help_text='Username if required', max_length=100)),
                ('sender_id', models.CharField(help_text='Sender ID or from number', max_length=20)),
                ('api_url', models.URLField(help_text='API endpoint URL')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT')], default='POST', max_length=4)),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('encryption', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('tls', 'TLS'), ('starttls', 'STARTTLS')], default='none', max_length=10)),
                ('default_encoding', models.CharField(default='UTF-8', help_text='Default message encoding', max_length=20)),
                ('max_message_length', models.IntegerField(default=160, help_text='Maximum message length')),
                ('support_unicode', models.BooleanField(default=True, help_text='Support for Unicode characters')),
                ('rate_limit_per_second', models.IntegerField(default=10, help_text='Messages per second limit')),
                ('rate_limit_per_minute', models.IntegerField(default=600, help_text='Messages per minute limit')),
                ('rate_limit_per_hour', models.IntegerField(default=36000, help_text='Messages per hour limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Gateway',
                'verbose_name_plural': 'SMS Gateways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_type', models.CharField(choices=[('connection', 'Connection Test'), ('authentication', 'Authentication Test'), ('message_send', 'Message Send Test'), ('delivery_status', 'Delivery Status Test'), ('unicode_test', 'Unicode/Encoding Test'), ('rate_limit', 'Rate Limit Test')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], default='pending', max_length=20)),
                ('test_message', models.TextField(help_text='Test message content')),
                ('recipient_number', models.CharField(help_text='Test recipient phone number', max_length=20)),
                ('message_encoding', models.CharField(default='UTF-8', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, help_text='HTTP response code', max_length=10)),
                ('response_message', models.TextField(blank=True, help_text='Response message from gateway')),
                ('error_message', models.TextField(blank=True, help_text='Error message if test failed')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('message_id', models.CharField(blank=True, help_text='Message ID from gateway', max_length=100)),
                ('delivery_status', models.CharField(blank=True, help_text='Delivery status from gateway', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test_environment', models.CharField(default='production', help_text='Test environment', max_length=50)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_tests_executed', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='sms_gateway.smsgateway')),
            ],
            options={
                'verbose_name': 'SMS Test Result',
                'verbose_name_plural': 'SMS Test Results',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_message_id', models.CharField(blank=True, help_text='Message ID from gateway', max_length=100)),
                ('recipient_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('sender_id', models.CharField(help_text='Sender ID', max_length=20)),
                ('message_content', models.TextField(help_text='SMS message content')),
                ('message_encoding', models.CharField(default='UTF-8', max_length=20)),
                ('message_length', models.IntegerField(help_text='Message length in characters')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled send time', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Message expiration time', null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('max_delivery_attempts', models.IntegerField(default=3)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Message cost', max_digits=10, null=True)),
                ('currency', models.CharField(default='AED', help_text='Cost currency', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Message tags for categorization')),
                ('category', models.CharField(blank=True, help_text='Message category', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages_created', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms_gateway.smsgateway')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSGatewayHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time', models.FloatField(help_text='Average response time in seconds')),
                ('success_rate', models.FloatField(help_text='Success rate percentage')),
                ('error_rate', models.FloatField(help_text='Error rate percentage')),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage', null=True)),
                ('active_connections', models.IntegerField(default=0, help_text='Active connections')),
                ('rate_limit_status', models.CharField(choices=[('normal', 'Normal'), ('approaching', 'Approaching Limit'), ('limited', 'Rate Limited')], default='normal', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='sms_gateway.smsgateway')),
            ],
            options={
                'verbose_name': 'SMS Gateway Health',
                'verbose_name_plural': 'SMS Gateway Health Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('undelivered', 'Undelivered')], max_length=20)),
                ('status_code', models.CharField(blank=True, help_text='Status code from gateway', max_length=10)),
                ('status_message', models.TextField(blank=True, help_text='Status message from gateway')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full gateway response')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Error details if any')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='sms_gateway.smsmessage')),
            ],
            options={
                'verbose_name': 'SMS Delivery Log',
                'verbose_name_plural': 'SMS Delivery Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
