# Generated by Django 4.2.23 on 2025-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttemplateitem',
            name='account_nature',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('BOTH', 'Both (Debit & Credit)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_nature',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('BOTH', 'Both (Debit & Credit)')], help_text='Normal balance side (optional - can be determined by account type)', max_length=10, null=True),
        ),
    ]
