# Generated by Django 4.2.23 on 2025-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_alter_accounttemplateitem_account_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_code',
            field=models.CharField(help_text='Unique account code (e.g., 1000, 1100)', max_length=20),
        ),
    ]
