# Generated by Django 4.2.23 on 2025-08-09 14:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('cost_center_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('budget_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Template',
                'verbose_name_plural': 'Budget Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_code', models.CharField(help_text='Unique budget code', max_length=50, unique=True)),
                ('budget_name', models.CharField(max_length=200)),
                ('fiscal_year', models.CharField(help_text='Fiscal year (e.g., 2024)', max_length=4)),
                ('budget_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Budget justification and notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Plan',
                'verbose_name_plural': 'Budget Plans',
                'ordering': ['-created_at'],
                'unique_together': {('budget_code',)},
            },
        ),
        migrations.CreateModel(
            name='BudgetImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('error_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Import',
                'verbose_name_plural': 'Budget Imports',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('import', 'Import')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='budget_planning.budgetplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Audit Log',
                'verbose_name_plural': 'Budget Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(choices=[('submit', 'Submit for Approval'), ('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return for Revision')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approvals', to=settings.AUTH_USER_MODEL)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='budget_planning.budgetplan')),
            ],
            options={
                'verbose_name': 'Budget Approval',
                'verbose_name_plural': 'Budget Approvals',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='chart_of_accounts.chartofaccount')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='cost_center_management.costcenter')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='budget_planning.budgettemplate')),
            ],
            options={
                'verbose_name': 'Budget Template Item',
                'verbose_name_plural': 'Budget Template Items',
                'ordering': ['cost_center__code', 'account__account_code'],
                'unique_together': {('template', 'cost_center', 'account')},
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='chart_of_accounts.chartofaccount')),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='budget_planning.budgetplan')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='cost_center_management.costcenter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_items', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='cost_center_management.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'ordering': ['cost_center__code', 'account__account_code'],
                'unique_together': {('budget_plan', 'cost_center', 'account')},
            },
        ),
    ]
