# Generated by Django 4.2.23 on 2025-08-09 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cost_center_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVarianceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('variance_threshold', 'Variance Threshold'), ('over_budget', 'Over Budget'), ('approaching_limit', 'Approaching Limit'), ('custom', 'Custom Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('threshold_percentage', models.DecimalField(decimal_places=2, help_text='Variance threshold percentage', max_digits=5)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Variance threshold amount', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_finance_managers', models.BooleanField(default=True)),
                ('notify_department_heads', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variance_alerts', to='cost_center_management.costcenter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variance_alerts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variance_alerts', to='cost_center_management.department')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='variance_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Variance Alert',
                'verbose_name_plural': 'Budget Variance Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVsActualReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('department', 'Department Report'), ('cost_center', 'Cost Center Report'), ('variance', 'Variance Report')], max_length=20)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField(default=dict, help_text='Stored report data')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('export_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_vs_actual_reports', to='cost_center_management.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_vs_actual_reports', to='cost_center_management.department')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_budget_vs_actual_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget vs Actual Report',
                'verbose_name_plural': 'Budget vs Actual Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVarianceNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='budget_planning.budgetvariancealert')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_notifications', to='budget_planning.budgetitem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Variance Notification',
                'verbose_name_plural': 'Budget Variance Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
