# Generated by Django 4.2.23 on 2025-08-09 06:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_add_supplier_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('jurisdiction_type', models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('city', 'City'), ('special_zone', 'Special Economic Zone')], default='country', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jurisdictions', to=settings.AUTH_USER_MODEL)),
                ('parent_jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_settings.taxjurisdiction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_jurisdictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction',
                'verbose_name_plural': 'Tax Jurisdictions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rounding_method', models.CharField(choices=[('nearest_001', 'Nearest 0.01'), ('nearest_005', 'Nearest 0.05'), ('nearest_010', 'Nearest 0.10'), ('no_rounding', 'No Rounding'), ('round_up', 'Round Up'), ('round_down', 'Round Down')], default='nearest_001', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_rates', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='tax_settings.taxjurisdiction')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VATReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('report_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchase_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('is_filed', models.BooleanField(default=False)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vat_reports', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_vat_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VAT Report',
                'verbose_name_plural': 'VAT Reports',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('tax_type', models.CharField(choices=[('standard_vat', 'Standard VAT'), ('zero_rated', 'Zero-Rated'), ('exempt', 'Exempt'), ('reverse_charge', 'Reverse Charge'), ('reduced_rate', 'Reduced Rate'), ('super_reduced_rate', 'Super Reduced Rate')], default='standard_vat', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_types', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Type',
                'verbose_name_plural': 'Tax Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('document_date', models.DateField()),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='customer.customer')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax_settings.taxrate')),
            ],
            options={
                'verbose_name': 'Tax Transaction',
                'verbose_name_plural': 'Tax Transactions',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxSettingsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Settings Audit Log',
                'verbose_name_plural': 'Tax Settings Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='tax_settings.taxtype'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupplierTaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=50)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('tax_exemption_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_tax_profiles', to=settings.AUTH_USER_MODEL)),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profiles', to='tax_settings.taxrate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_tax_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Tax Profile',
                'verbose_name_plural': 'Supplier Tax Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductTaxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_tax_categories', to=settings.AUTH_USER_MODEL)),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='tax_settings.taxrate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_tax_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Tax Category',
                'verbose_name_plural': 'Product Tax Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=50)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('tax_exemption_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_tax_profiles', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='customer.customer')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='tax_settings.taxrate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_tax_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Tax Profile',
                'verbose_name_plural': 'Customer Tax Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('tax_type', 'jurisdiction', 'effective_from')},
        ),
    ]
