# Generated by Django 4.2.23 on 2025-08-09 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFilingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('filing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('total_output_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_input_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('output_transactions_count', models.IntegerField(default=0)),
                ('input_transactions_count', models.IntegerField(default=0)),
                ('adjustment_transactions_count', models.IntegerField(default=0)),
                ('has_missing_vat_numbers', models.BooleanField(default=False)),
                ('has_mismatched_rates', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('submitted', 'Submitted'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('filing_reference', models.CharField(blank=True, max_length=100)),
                ('filing_date', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tax_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tax_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Filing Report',
                'verbose_name_plural': 'Tax Filing Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFilingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('transaction_type', models.CharField(choices=[('output', 'Output Tax (Sales)'), ('input', 'Input Tax (Purchases)'), ('adjustment', 'Adjustment')], max_length=20)),
                ('adjustment_type', models.CharField(blank=True, choices=[('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('refund', 'Refund'), ('write_off', 'Write-off'), ('correction', 'Correction')], max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('has_vat_number', models.BooleanField(default=True)),
                ('vat_rate_matches', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('original_transaction_id', models.CharField(blank=True, max_length=100)),
                ('original_transaction_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax_filing.taxfilingreport')),
            ],
            options={
                'verbose_name': 'Tax Filing Transaction',
                'verbose_name_plural': 'Tax Filing Transactions',
                'ordering': ['transaction_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='TaxFilingValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation_type', models.CharField(choices=[('missing_vat_number', 'Missing VAT Number'), ('mismatched_rate', 'Mismatched VAT Rate'), ('invalid_amount', 'Invalid Amount'), ('duplicate_invoice', 'Duplicate Invoice'), ('date_out_of_range', 'Date Out of Range')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('expected_value', models.CharField(blank=True, max_length=255)),
                ('actual_value', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='tax_filing.taxfilingreport')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_validations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='tax_filing.taxfilingtransaction')),
            ],
            options={
                'verbose_name': 'Tax Filing Validation',
                'verbose_name_plural': 'Tax Filing Validations',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFilingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_authority_name', models.CharField(default='Local Tax Authority', max_length=200)),
                ('tax_authority_code', models.CharField(blank=True, max_length=50)),
                ('filing_deadline_days', models.IntegerField(default=28)),
                ('auto_validation', models.BooleanField(default=True)),
                ('require_vat_numbers', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='AED', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_filing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Filing Setting',
                'verbose_name_plural': 'Tax Filing Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxFilingExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('xml', 'XML')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_tax_filings', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='tax_filing.taxfilingreport')),
            ],
            options={
                'verbose_name': 'Tax Filing Export',
                'verbose_name_plural': 'Tax Filing Exports',
                'ordering': ['-exported_at'],
            },
        ),
    ]
