# Generated by Django 4.2.23 on 2025-08-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_currency', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency'),
        ),
    ]
