# Generated by Django 4.2.23 on 2025-07-09 07:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('multi_currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt_voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('deposit_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency')),
                ('deposit_to', models.ForeignKey(limit_choices_to={'account_type__category': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips', to='chart_of_accounts.chartofaccount')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Slip',
                'verbose_name_plural': 'Deposit Slips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositSlipAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('item_added', 'Item Added'), ('item_removed', 'Item Removed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deposit_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='deposit_slip.depositslip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Slip Audit',
                'verbose_name_plural': 'Deposit Slip Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DepositSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deposit_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deposit_slip.depositslip')),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slip_items', to='receipt_voucher.receiptvoucher')),
            ],
            options={
                'verbose_name': 'Deposit Slip Item',
                'verbose_name_plural': 'Deposit Slip Items',
                'ordering': ['created_at'],
                'unique_together': {('deposit_slip', 'receipt_voucher')},
            },
        ),
    ]
