# Generated by Django 4.2.23 on 2025-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('supplier', 'Supplier'), ('other', 'Other')], default='other', max_length=20, verbose_name='Company Type'),
        ),
    ]
