# Generated by Django 4.2.23 on 2025-07-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
