# Generated by Django 4.2.23 on 2025-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT/BIC Code'),
        ),
    ]
