# Generated by Django 5.0.2 on 2025-08-16 19:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_add_bank_details'),
        ('customer', '0007_add_supplier_customer_type'),
        ('customer_payments', '0004_customerpayment_ledger_account'),
        ('fiscal_year', '0001_initial'),
        ('invoice', '0010_auto_20250814_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLedgerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text='Name for this report configuration', max_length=100)),
                ('date_from', models.DateField(help_text='Start date for the report')),
                ('date_to', models.DateField(help_text='End date for the report')),
                ('payment_status', models.CharField(choices=[('all', 'All'), ('pending', 'Pending'), ('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid')], default='all', help_text='Payment status filter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_ledger_reports_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Specific customer (leave blank for all customers)', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal_year.fiscalyear')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_ledger_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Ledger Report',
                'verbose_name_plural': 'Partner Ledger Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('adjustment', 'Adjustment')], max_length=20)),
                ('entry_date', models.DateField()),
                ('reference_number', models.CharField(help_text='Invoice number, payment number, etc.', max_length=50)),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal_year.fiscalyear')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_payments.customerpayment')),
            ],
            options={
                'verbose_name': 'Partner Ledger Entry',
                'verbose_name_plural': 'Partner Ledger Entries',
                'ordering': ['customer', 'entry_date', 'created_at'],
                'indexes': [models.Index(fields=['customer', 'entry_date'], name='partner_led_custome_954402_idx'), models.Index(fields=['entry_type'], name='partner_led_entry_t_5bd8aa_idx'), models.Index(fields=['reference_number'], name='partner_led_referen_2e1229_idx'), models.Index(fields=['company', 'fiscal_year'], name='partner_led_company_42cdf4_idx')],
            },
        ),
    ]
