# Generated by Django 4.2.23 on 2025-08-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_currency', '0001_initial'),
        ('customer', '0007_add_supplier_customer_type'),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('payment_source', '0003_update_existing_payment_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='category',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit_card', 'Credit Card'), ('advance_account', 'Advance Account'), ('other_payable', 'Other Payable')], default='other_payable', help_text='Category of payment source', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='code',
            field=models.CharField(blank=True, help_text='Unique short code for this payment source', max_length=20, null=True, unique=True, verbose_name='Short Code'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for this payment source (required if multi-currency is enabled)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multi_currency.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='default_expense_ledger',
            field=models.ForeignKey(blank=True, help_text='Default expense account for this payment source (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_expense_payment_sources', to='chart_of_accounts.chartofaccount', verbose_name='Default Expense Ledger'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='default_vendor',
            field=models.ForeignKey(blank=True, help_text='Default vendor for this payment source (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Default Vendor'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='linked_ledger',
            field=models.ForeignKey(blank=True, help_text='Chart of Account linked to this payment source (required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ledger_payment_sources', to='chart_of_accounts.chartofaccount', verbose_name='Linked Ledger'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='source_type',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], default='postpaid', help_text='Type of payment source', max_length=20, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status (Legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='linked_account',
            field=models.ForeignKey(blank=True, help_text='Chart of Account linked to this payment source (legacy field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_account_payment_sources', to='chart_of_accounts.chartofaccount', verbose_name='Linked Account (Legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Payment Source Name'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentsource',
            unique_together={('name', 'code')},
        ),
    ]
