# Generated by Django 4.2.23 on 2025-07-08 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('fiscal_year', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_balances', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='fiscal_year.fiscalyear', verbose_name='Financial Year')),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'ordering': ['-created_at'],
                'unique_together': {('financial_year',)},
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('balance_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6, verbose_name='Balance Type')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_entries', to='chart_of_accounts.chartofaccount', verbose_name='Account')),
                ('opening_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='opening_balance.openingbalance', verbose_name='Opening Balance')),
            ],
            options={
                'verbose_name': 'Opening Balance Entry',
                'verbose_name_plural': 'Opening Balance Entries',
                'ordering': ['account__account_code'],
                'unique_together': {('opening_balance', 'account')},
            },
        ),
    ]
