# Generated by Django 4.2.23 on 2025-07-08 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('opening_balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalanceentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_entries', to='chart_of_accounts.chartofaccount', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='openingbalanceentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
    ]
