# Generated by Django 4.2.23 on 2025-07-08 16:04

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('company', '0003_remove_company_company_type'),
        ('customer', '0007_add_supplier_customer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(help_text='Cheque number', max_length=50)),
                ('cheque_date', models.DateField(help_text='Date on the cheque')),
                ('cheque_type', models.CharField(choices=[('issued', 'Issued'), ('received', 'Received')], help_text='Type of cheque', max_length=10)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], help_text='Type of party', max_length=10)),
                ('supplier', models.CharField(blank=True, help_text='Supplier name', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cheque amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('related_transaction', models.CharField(blank=True, help_text='Related payment/receipt voucher', max_length=200, null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped')], default='pending', help_text='Current status of the cheque', max_length=10)),
                ('clearing_date', models.DateField(blank=True, help_text='Date when cheque was cleared', null=True)),
                ('stop_payment_date', models.DateField(blank=True, help_text='Date when stop payment was requested', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('is_post_dated', models.BooleanField(default=False, help_text='Whether this is a post-dated cheque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account', on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='chart_of_accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_registers', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cheques', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='customer.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cheques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Register',
                'verbose_name_plural': 'Cheque Registers',
                'ordering': ['-cheque_date', '-created_at'],
                'unique_together': {('cheque_number', 'bank_account', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ChequeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped')], max_length=10, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cheque_register.chequeregister')),
            ],
            options={
                'verbose_name': 'Cheque Status History',
                'verbose_name_plural': 'Cheque Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChequeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('post_dated_due', 'Post-dated Cheque Due'), ('overdue', 'Overdue Cheque'), ('bounced', 'Cheque Bounced'), ('cleared', 'Cheque Cleared')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cheque_register.chequeregister')),
            ],
            options={
                'verbose_name': 'Cheque Alert',
                'verbose_name_plural': 'Cheque Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
