# Generated by Django 4.2.23 on 2025-07-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_company_type'),
        ('cheque_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeregister',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_registers', to='company.company'),
        ),
    ]
