# Generated by Django 5.0.2 on 2025-08-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('duplicate_detection', 'Duplicate Detection'), ('format_validation', 'Format Validation'), ('mandatory_field_check', 'Mandatory Field Check'), ('data_type_validation', 'Data Type Validation'), ('business_rule_validation', 'Business Rule Validation')], max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_field', models.CharField(blank=True, max_length=100)),
                ('rule_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedCleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cleaning_type', models.CharField(choices=[('master_data', 'Master Data'), ('financial_data', 'Financial Data'), ('transactional_data', 'Transactional Data'), ('comprehensive', 'Comprehensive')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataCleaningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cleaning_type', models.CharField(choices=[('master_data', 'Master Data'), ('financial_data', 'Financial Data'), ('transactional_data', 'Transactional Data'), ('comprehensive', 'Comprehensive')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_records_scanned', models.IntegerField(default=0)),
                ('total_records_cleaned', models.IntegerField(default=0)),
                ('total_errors_found', models.IntegerField(default=0)),
                ('total_warnings_found', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCleaningAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('record_merged', 'Record Merged'), ('field_updated', 'Field Updated'), ('validation_error', 'Validation Error'), ('warning_generated', 'Warning Generated')], max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_record_id', models.CharField(max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_cleaning_tool.datacleaningrule')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_cleaning_tool.datacleaningsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField(default=dict)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_cleaning_tool.datacleaningsession')),
            ],
        ),
    ]
