# Generated by Django 5.0.2 on 2025-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cleaning_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacleaningsession',
            name='archive_old',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='batch_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='create_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='custom_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='fill_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='remove_duplicates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='standardize_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacleaningsession',
            name='validate_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automatedcleaningschedule',
            name='cleaning_type',
            field=models.CharField(choices=[('master', 'Master Data'), ('transactional', 'Transactional Data'), ('financial', 'Financial Data'), ('comprehensive', 'Comprehensive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datacleaningsession',
            name='cleaning_type',
            field=models.CharField(choices=[('master', 'Master Data'), ('transactional', 'Transactional Data'), ('financial', 'Financial Data'), ('comprehensive', 'Comprehensive')], max_length=50),
        ),
    ]
