# Generated by Django 4.2.23 on 2025-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
