# Generated by Django 4.2.23 on 2025-07-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('company', '0003_remove_company_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('template_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_balance_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('as_of_date', models.DateField()),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('report_data', models.JSONField(default=dict)),
                ('include_headers', models.BooleanField(default=True)),
                ('include_totals', models.BooleanField(default=True)),
                ('include_comparison', models.BooleanField(default=False)),
                ('include_percentages', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_balance_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance Sheet Report',
                'verbose_name_plural': 'Balance Sheet Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('current_assets', 'Current Assets'), ('non_current_assets', 'Non-Current Assets'), ('current_liabilities', 'Current Liabilities'), ('non_current_liabilities', 'Non-Current Liabilities'), ('equity', 'Equity')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='balance_groups', to='chart_of_accounts.chartofaccount')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='balance_sheet.accountgroup')),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
                'ordering': ['asset_type', 'order', 'name'],
            },
        ),
    ]
