# Generated by Django 5.0.2 on 2025-08-16 22:53

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivableAgingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(blank=True, max_length=50)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('days_1_30', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('days_31_60', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('days_61_90', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('days_over_90', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_receivable_aging_report',
                'ordering': ['-report_date', 'customer_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('days_outstanding', models.IntegerField(default=0)),
                ('aging_bucket', models.CharField(choices=[('current', 'Current'), ('1-30', '1-30 Days'), ('31-60', '31-60 Days'), ('61-90', '61-90 Days'), ('over_90', 'Over 90 Days')], max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_invoice_aging',
                'ordering': ['-report_date', 'customer_name', '-invoice_date'],
            },
        ),
    ]
