# Generated by Django 4.2.23 on 2025-07-07 14:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi_currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, help_text='Auto-generated voucher number', max_length=20, unique=True)),
                ('voucher_date', models.DateField(help_text='Date of the payment voucher')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('payee_type', models.CharField(choices=[('vendor', 'Vendor'), ('employee', 'Employee'), ('other', 'Other')], default='vendor', max_length=20)),
                ('payee_name', models.CharField(help_text='Name of the payee', max_length=200)),
                ('payee_id', models.CharField(blank=True, help_text='ID/Code of the payee', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Description or remarks for the payment')),
                ('reference_invoices', models.TextField(blank=True, help_text='Reference to related invoices')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_to_debit', models.ForeignKey(help_text='Account to be debited for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_vouchers_debited', to='chart_of_accounts.chartofaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multi_currency.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Voucher',
                'verbose_name_plural': 'Payment Vouchers',
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucherAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='payment_voucher.paymentvoucher')),
            ],
            options={
                'verbose_name': 'Payment Voucher Audit',
                'verbose_name_plural': 'Payment Voucher Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucherAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_vouchers/attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payment_voucher.paymentvoucher')),
            ],
            options={
                'verbose_name': 'Payment Voucher Attachment',
                'verbose_name_plural': 'Payment Voucher Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
