# Generated by Django 4.2.23 on 2025-08-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('arabic_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('signed', 'Signed'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hr_letters/')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='hr_letters/signed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_letters', to='employees.employee')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Letter',
                'verbose_name_plural': 'Generated Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20)),
            ],
            options={
                'verbose_name': 'Letter Placeholder',
                'verbose_name_plural': 'Letter Placeholders',
            },
        ),
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Letter Type',
                'verbose_name_plural': 'Letter Types',
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('both', 'English & Arabic')], default='en', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Use placeholders like {{employee_name}}, {{designation}}, {{salary}}, etc.')),
                ('arabic_content', models.TextField(blank=True, help_text='Arabic version of the content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='hr_letters_documents.lettertype')),
            ],
            options={
                'verbose_name': 'Letter Template',
                'verbose_name_plural': 'Letter Templates',
            },
        ),
        migrations.CreateModel(
            name='LetterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('finalized', 'Finalized'), ('signed', 'Signed'), ('issued', 'Issued'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hr_letters_documents.generatedletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter History',
                'verbose_name_plural': 'Letter History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='hr_documents/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr_letters_documents.documentcategory')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Document',
                'verbose_name_plural': 'HR Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='letter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_letters_documents.lettertype'),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_letters_documents.lettertemplate'),
        ),
        migrations.CreateModel(
            name='LetterApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_approvals', to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hr_letters_documents.generatedletter')),
            ],
            options={
                'verbose_name': 'Letter Approval',
                'verbose_name_plural': 'Letter Approvals',
                'unique_together': {('letter', 'approver')},
            },
        ),
    ]
