# Generated by Django 4.2.23 on 2025-08-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMovementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_approval', models.BooleanField(default=False, help_text='Require approval for asset movements')),
                ('auto_approve_assignments', models.BooleanField(default=True, help_text='Auto-approve asset assignments')),
                ('require_reason', models.BooleanField(default=True, help_text='Require reason for all movements')),
                ('max_duration_days', models.PositiveIntegerField(default=365, help_text='Maximum allowed movement duration in days')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable email notifications for movements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Movement Setting',
                'verbose_name_plural': 'Asset Movement Settings',
            },
        ),
        migrations.CreateModel(
            name='AssetMovementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('movement_type', models.CharField(choices=[('transfer', 'Transfer'), ('assignment', 'Assignment'), ('return', 'Return'), ('disposal', 'Disposal'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('relocation', 'Relocation'), ('other', 'Other')], max_length=20)),
                ('movement_reason', models.CharField(choices=[('operational', 'Operational Need'), ('maintenance', 'Maintenance/Repair'), ('inspection', 'Inspection/Audit'), ('relocation', 'Office Relocation'), ('disposal', 'Asset Disposal'), ('assignment', 'Employee Assignment'), ('return', 'Asset Return'), ('other', 'Other')], max_length=20)),
                ('default_notes', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMovementLog',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('transfer', 'Transfer'), ('assignment', 'Assignment'), ('return', 'Return'), ('disposal', 'Disposal'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('relocation', 'Relocation'), ('other', 'Other')], default='transfer', max_length=20)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_reason', models.CharField(choices=[('operational', 'Operational Need'), ('maintenance', 'Maintenance/Repair'), ('inspection', 'Inspection/Audit'), ('relocation', 'Office Relocation'), ('disposal', 'Asset Disposal'), ('assignment', 'Employee Assignment'), ('return', 'Asset Return'), ('other', 'Other')], default='operational', max_length=20)),
                ('reason_description', models.TextField(blank=True, help_text='Detailed reason for the movement')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the movement')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in days', null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movement_logs_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='asset_register.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs_from', to='asset_register.assetlocation')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movement_logs_from', to=settings.AUTH_USER_MODEL)),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_movement_logs_created', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs_to', to='asset_register.assetlocation')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movement_logs_to', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_logs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Movement Log',
                'verbose_name_plural': 'Asset Movement Logs',
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['asset'], name='asset_movem_asset_i_d2a6ef_idx'), models.Index(fields=['movement_date'], name='asset_movem_movemen_850662_idx'), models.Index(fields=['movement_type'], name='asset_movem_movemen_1de2c8_idx'), models.Index(fields=['from_location'], name='asset_movem_from_lo_f69eb4_idx'), models.Index(fields=['to_location'], name='asset_movem_to_loca_6f6ff1_idx'), models.Index(fields=['moved_by'], name='asset_movem_moved_b_a1a922_idx')],
            },
        ),
    ]
