# Generated by Django 4.2.23 on 2025-07-07 14:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
        ('multi_currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('receipt_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('online_payment', 'Online Payment'), ('other', 'Other')], max_length=20)),
                ('payer_type', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=20)),
                ('payer_name', models.CharField(max_length=200)),
                ('payer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_invoices', models.TextField(blank=True, help_text='Comma-separated invoice numbers', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account_to_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.chartofaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multi_currency.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Voucher',
                'verbose_name_plural': 'Receipt Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('marked_received', 'Marked as Received'), ('cancelled', 'Cancelled'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='receipt_voucher.receiptvoucher')),
            ],
            options={
                'verbose_name': 'Receipt Voucher Audit',
                'verbose_name_plural': 'Receipt Voucher Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipt_vouchers/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='receipt_voucher.receiptvoucher')),
            ],
            options={
                'verbose_name': 'Receipt Voucher Attachment',
                'verbose_name_plural': 'Receipt Voucher Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
