# Generated by Django 4.2.23 on 2025-06-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman', '0002_alter_salesman_phone'),
        ('facility', '0002_facilitylocation'),
        ('grn', '0009_grnpallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('customer', '0006_customer_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='DO Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('customer_ref', models.CharField(blank=True, max_length=100, verbose_name='Customer Reference')),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_contact', models.CharField(blank=True, max_length=100, verbose_name='Delivery Contact')),
                ('delivery_phone', models.CharField(blank=True, max_length=50, verbose_name='Delivery Phone')),
                ('delivery_email', models.EmailField(blank=True, max_length=254, verbose_name='Delivery Email')),
                ('do_date', models.DateField(default=django.utils.timezone.now, verbose_name='DO Date')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='Requested Delivery Date')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Actual Delivery Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('shipping_method', models.CharField(blank=True, max_length=50, verbose_name='Shipping Method')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking Number')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Carrier')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Quantity')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Weight (KGS)')),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Volume (CBM)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_delivery_orders', to='salesman.salesman', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility', verbose_name='Facility')),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grn.grn', verbose_name='Related GRN')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Requested Quantity')),
                ('shipped_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipped Quantity')),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivered Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_order.deliveryorder', verbose_name='Delivery Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Item')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facilitylocation', verbose_name='Source Location')),
            ],
            options={
                'verbose_name': 'Delivery Order Item',
                'verbose_name_plural': 'Delivery Order Items',
                'unique_together': {('delivery_order', 'item')},
            },
        ),
    ]
