# Generated by Django 4.2.23 on 2025-06-26 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='bill_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bill To'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='bill_to_address',
            field=models.TextField(blank=True, verbose_name='Bill to Address'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='bl_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='BL Number'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='boe',
            field=models.CharField(blank=True, max_length=50, verbose_name='BOE'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='container',
            field=models.CharField(blank=True, max_length=50, verbose_name='Container'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='deliver_to_address',
            field=models.TextField(blank=True, verbose_name='Deliver to Address'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=200, verbose_name='Delivery Terms'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='discharge_port',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discharge Port'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='exit_point',
            field=models.CharField(blank=True, max_length=100, verbose_name='Exit Point'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Payment Mode'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Port of Loading'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='ship_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ship Date'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='ship_mode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ship Mode'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vessel'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='voyage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Voyage'),
        ),
    ]
