# Generated by Django 4.2.23 on 2025-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0002_deliveryorder_bill_to_deliveryorder_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Delivery Address'),
        ),
    ]
