# Generated by Django 4.2.23 on 2025-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0003_alter_deliveryorder_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='deliveryorderitem',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Date'),
        ),
    ]
