# Generated by Django 4.2.23 on 2025-06-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0004_deliveryorderitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='facility_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Facility Email'),
        ),
    ]
