# Generated by Django 4.2.23 on 2025-06-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0005_deliveryorder_facility_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='facility_email',
        ),
    ]
