# Generated by Django 4.2.23 on 2025-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bl_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bill of Lading Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignee',
            field=models.CharField(blank=True, max_length=200, verbose_name='Consignee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='container_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Container Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ed_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entry Declaration Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_count',
            field=models.IntegerField(default=0, verbose_name='Number of Items'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipper',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shipper'),
        ),
    ]
