# Generated by Django 4.2.23 on 2025-06-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_bl_number_invoice_consignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bill_to_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amount',
        ),
    ]
