# Generated by Django 4.2.23 on 2025-06-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_bill_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
