# Generated by Django 4.2.23 on 2025-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobcontainer'),
        ('invoice', '0004_delete_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='job',
        ),
        migrations.AddField(
            model_name='invoice',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='job.job', verbose_name='Jobs'),
        ),
    ]
