# Generated by Django 4.2.23 on 2025-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_invoice_job_invoice_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items_count',
            field=models.CharField(blank=True, max_length=500, verbose_name='Items'),
        ),
    ]
