# Generated by Django 4.2.23 on 2025-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Quantity'),
        ),
    ]
