# Generated by Django 4.2.23 on 2025-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bill To'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address',
            field=models.TextField(blank=True, verbose_name='Bill To Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_items',
            field=models.JSONField(blank=True, default=list, verbose_name='Invoice Items'),
        ),
    ]
