# Generated by Django 4.2.23 on 2025-07-07 07:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_remove_company_company_type'),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('report_title', models.CharField(default='Trial Balance Report', max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_balanced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_reports', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_balance_reports_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_balance_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trial Balance Report',
                'verbose_name_plural': 'Trial Balance Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('period_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('period_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('account_category', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_entries', to='chart_of_accounts.chartofaccount')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trial_balance.trialbalancereport')),
            ],
            options={
                'verbose_name': 'Trial Balance Entry',
                'verbose_name_plural': 'Trial Balance Entries',
                'ordering': ['account_code'],
                'unique_together': {('report', 'account')},
            },
        ),
    ]
