# Generated by Django 4.2.23 on 2025-07-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalancereport',
            name='company',
        ),
        migrations.RemoveField(
            model_name='trialbalancereport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trialbalancereport',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='TrialBalanceEntry',
        ),
        migrations.DeleteModel(
            name='TrialBalanceReport',
        ),
    ]
