# Generated by Django 4.2.23 on 2025-07-08 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_company_company_type'),
        ('multi_currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chart_of_accounts', '0003_alter_chartofaccount_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=200)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('loan', 'Loan Account'), ('overdraft', 'Overdraft Account'), ('credit_card', 'Credit Card'), ('term_deposit', 'Term Deposit')], default='current', max_length=20)),
                ('branch_name', models.CharField(blank=True, help_text='Branch name', max_length=200, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC/SWIFT code', max_length=20, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_default_for_payments', models.BooleanField(default=False, help_text='Default account for payments')),
                ('is_default_for_receipts', models.BooleanField(default=False, help_text='Default account for receipts')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the account', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.ForeignKey(help_text='Link to Chart of Account (Bank-type ledgers only)', limit_choices_to={'account_type__category': 'ASSET'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='chart_of_accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='multi_currency.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['bank_name', 'account_number'],
                'unique_together': {('account_number', 'company')},
            },
        ),
        migrations.CreateModel(
            name='BankAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_accounts.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account Transaction',
                'verbose_name_plural': 'Bank Account Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
