# Generated by Django 4.2.23 on 2025-08-09 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_add_supplier_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hbl_number', models.CharField(help_text='Unique HBL number', max_length=50, unique=True)),
                ('mbl_number', models.CharField(blank=True, help_text='Master Bill of Lading number', max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Original', 'Original'), ('SEAWAY BILL', 'SEAWAY BILL')], default='Draft', max_length=20)),
                ('shipped_on_board', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre_carriage_by', models.CharField(default='BY SEA', max_length=100)),
                ('place_of_receipt', models.CharField(blank=True, max_length=200)),
                ('ocean_vessel', models.CharField(blank=True, max_length=200)),
                ('port_of_loading', models.CharField(blank=True, max_length=200)),
                ('port_of_discharge', models.CharField(blank=True, max_length=200)),
                ('place_of_delivery', models.CharField(blank=True, max_length=200)),
                ('terms', models.CharField(blank=True, choices=[('FCL/FCL', 'FCL/FCL'), ('FCL/LCL', 'FCL/LCL'), ('LCL/LCL', 'LCL/LCL'), ('LCL/FCL', 'LCL/FCL'), ('RO-RO', 'RO-RO'), ('Break Bulk', 'Break Bulk')], max_length=20)),
                ('description_of_goods', models.TextField(blank=True)),
                ('number_of_packages', models.IntegerField(default=0)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in KGS', max_digits=10)),
                ('measurement', models.DecimalField(decimal_places=2, default=0.0, help_text='Volume in CBM', max_digits=10)),
                ('freight_prepaid', models.BooleanField(default=False)),
                ('freight_collect', models.BooleanField(default=False)),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('remarks', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hbls_as_consignee', to='customer.customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hbls', to=settings.AUTH_USER_MODEL)),
                ('notify_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hbls_as_notify_party', to='customer.customer')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hbls_as_shipper', to='customer.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hbls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Bill of Lading',
                'verbose_name_plural': 'House Bills of Lading',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HBLReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('custom', 'Custom Report')], max_length=20)),
                ('filters', models.JSONField(default=dict, help_text='Report filters applied')),
                ('report_data', models.JSONField(default=dict, help_text='Stored report data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HBL Report',
                'verbose_name_plural': 'HBL Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='HBLItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_no', models.CharField(blank=True, max_length=50)),
                ('container_size', models.CharField(blank=True, choices=[('20STD', '20STD'), ('40STD', '40STD'), ('40HC', '40HC'), ('45HC', '45HC')], max_length=10)),
                ('seal_no', models.CharField(blank=True, max_length=50)),
                ('number_of_packages', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('package_type', models.CharField(blank=True, choices=[('CTN', 'CTN'), ('PLT', 'PLT'), ('CASE', 'CASE'), ('PCS', 'PCS'), ('OTHER', 'OTHER')], max_length=20)),
                ('custom_package_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('gross_weight', models.DecimalField(decimal_places=2, help_text='Weight in KGS', max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, help_text='Weight in KGS', max_digits=10)),
                ('measurement', models.DecimalField(decimal_places=2, help_text='Volume in CBM', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='bill_of_lading.hbl')),
            ],
            options={
                'verbose_name': 'HBL Cargo Item',
                'verbose_name_plural': 'HBL Cargo Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HBLHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('cargo_added', 'Cargo Added'), ('cargo_updated', 'Cargo Updated'), ('cargo_deleted', 'Cargo Deleted'), ('charges_added', 'Charges Added'), ('charges_updated', 'Charges Updated'), ('charges_deleted', 'Charges Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bill_of_lading.hbl')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HBL History',
                'verbose_name_plural': 'HBL History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HBLCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('freight', 'Freight'), ('thc', 'THC'), ('doc_fee', 'Documentation Fee'), ('cfs', 'CFS'), ('customs', 'Customs'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='bill_of_lading.hbl')),
            ],
            options={
                'verbose_name': 'HBL Charge',
                'verbose_name_plural': 'HBL Charges',
                'ordering': ['created_at'],
            },
        ),
    ]
