# Generated by Django 4.2.23 on 2025-06-21 13:09

from django.db import migrations

def create_job_types(apps, schema_editor):
    JobType = apps.get_model('job', 'JobType')
    job_types = [
        {'name': 'Inbound', 'description': 'Jobs related to incoming shipments and receiving operations', 'is_active': True},
        {'name': 'Warehouse', 'description': 'Jobs related to warehouse operations and storage management', 'is_active': True},
        {'name': 'Documentation', 'description': 'Jobs related to document processing and compliance', 'is_active': True},
        {'name': 'Cross Stuffing', 'description': 'Jobs related to cross stuffing operations and container transfers', 'is_active': True},
    ]
    for job_type in job_types:
        JobType.objects.get_or_create(name=job_type['name'], defaults=job_type)

def reverse_job_types(apps, schema_editor):
    JobType = apps.get_model('job', 'JobType')
    names = ['Inbound', 'Warehouse', 'Documentation', 'Cross Stuffing']
    JobType.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('job', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_job_types, reverse_job_types),
    ]
