# Generated by Django 4.2.23 on 2025-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_add_job_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='broker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('TOO', 'TOO'), ('Transit IN', 'Transit IN'), ('Transit OUT', 'Transit OUT'), ('Import', 'Import'), ('Export', 'Export')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('FCL-FCL', 'FCL-FCL'), ('FCL-LCL', 'FCL-LCL'), ('LCL-LCL', 'LCL-LCL'), ('BULK', 'BULK'), ('RO-RO', 'RO-RO')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='shipper',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
