# Generated by Django 4.2.23 on 2025-06-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facilitylocation'),
        ('customer', '0005_alter_customer_portal_username'),
        ('job', '0003_job_broker_job_customer_name_job_customer_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='job',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_broker', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_shipper', to='customer.customer'),
        ),
    ]
