# Generated by Django 4.2.23 on 2025-06-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_description_alter_job_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coo', models.CharField(blank=True, max_length=100)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='job.job')),
            ],
            options={
                'verbose_name': 'Job Cargo',
                'verbose_name_plural': 'Job Cargo',
                'ordering': ['created_at'],
            },
        ),
    ]
