# Generated by Django 4.2.23 on 2025-06-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_item_type_item_item_category'),
        ('facility', '0002_facilitylocation'),
        ('job', '0006_add_job_cargo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcargo',
            name='description',
        ),
        migrations.AddField(
            model_name='jobcargo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cargo_items', to='items.item'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='doc_type',
            field=models.CharField(choices=[('TOO', 'TOO'), ('Transit IN', 'Transit IN'), ('Transit OUT', 'Transit OUT'), ('Import', 'Import'), ('Export', 'Export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='job',
            name='shipment_type',
            field=models.CharField(choices=[('FCL-FCL', 'FCL-FCL'), ('FCL-LCL', 'FCL-LCL'), ('LCL-LCL', 'LCL-LCL'), ('BULK', 'BULK'), ('RO-RO', 'RO-RO')], max_length=20),
        ),
    ]
