# Generated by Django 4.2.23 on 2025-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facilitylocation'),
        ('job', '0007_remove_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='facility.facility'),
        ),
    ]
