# Generated by Django 4.2.23 on 2025-06-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_alter_salesman_phone'),
        ('job', '0008_remove_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Land', 'Land'), ('Air', 'Air')], default='Sea', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='salesman.salesman'),
        ),
        migrations.AlterField(
            model_name='job',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
