# Generated by Django 4.2.23 on 2025-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_mode_alter_job_assigned_to_alter_job_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Warehousing', 'Warehousing'), ('Documentations', 'Documentations'), ('Cross Stuffing', 'Cross Stuffing')], max_length=20),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
