# Generated by Django 4.2.23 on 2025-06-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_bl_consignee_job_bl_notify_party_job_bl_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('m1_number', models.CharField(blank=True, max_length=100, null=True)),
                ('container_number', models.CharField(blank=True, max_length=100, null=True)),
                ('container_size', models.CharField(blank=True, max_length=50, null=True)),
                ('seal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='job.job')),
            ],
            options={
                'verbose_name': 'Job Container',
                'verbose_name_plural': 'Job Containers',
                'ordering': ['created_at'],
            },
        ),
    ]
