# Generated by Django 4.2.23 on 2025-08-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_add_in_process_status'),
        ('job', '0012_jobcontainer'),
    ]

    operations = [
    ]
