# Generated by Django 4.2.23 on 2025-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_merge_0003_add_in_process_status_0012_jobcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
