# Generated by Django 4.2.23 on 2025-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_vessel_name_job_voyage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mrn_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcontainer',
            name='cargo_bond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
