# Generated by Django 4.2.23 on 2025-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_mrn_number_jobcontainer_cargo_bond'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fz_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
