# Generated by Django 4.2.23 on 2025-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_fz_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='com_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='com_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
