# Generated by Django 5.0.2 on 2025-08-09 23:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_log', models.JSONField(default=list)),
                ('import_summary', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='import_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_file', to='master_data_import.importjob')),
            ],
            options={
                'verbose_name': 'Import File',
                'verbose_name_plural': 'Import Files',
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(blank=True, max_length=100)),
                ('error_type', models.CharField(choices=[('validation', 'Validation Error'), ('duplicate', 'Duplicate Error'), ('reference', 'Reference Error'), ('format', 'Format Error'), ('system', 'System Error')], max_length=20)),
                ('error_message', models.TextField()),
                ('field_value', models.TextField(blank=True)),
                ('suggested_correction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='master_data_import.importjob')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'ordering': ['import_job', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('validate', 'Data Validation'), ('import', 'Data Import'), ('error', 'Error Occurred'), ('complete', 'Import Complete')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='master_data_import.importjob')),
            ],
            options={
                'verbose_name': 'Import Audit Log',
                'verbose_name_plural': 'Import Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('customers', 'Customers'), ('vendors', 'Vendors'), ('products', 'Products'), ('chart_of_accounts', 'Chart of Accounts'), ('employees', 'Employees'), ('inventory_items', 'Inventory Items'), ('price_lists', 'Price Lists')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('column_mappings', models.JSONField(default=dict)),
                ('validation_rules', models.JSONField(default=dict)),
                ('required_fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Template',
                'verbose_name_plural': 'Import Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='importjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='master_data_import.importtemplate'),
        ),
        migrations.CreateModel(
            name='ImportValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('required', 'Required Field'), ('unique', 'Unique Value'), ('format', 'Format Validation'), ('range', 'Range Validation'), ('reference', 'Foreign Key Reference'), ('custom', 'Custom Validation')], max_length=20)),
                ('validation_type', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone Number'), ('date', 'Date'), ('number', 'Number'), ('decimal', 'Decimal'), ('url', 'URL'), ('regex', 'Regular Expression')], max_length=20)),
                ('rule_config', models.JSONField(default=dict)),
                ('error_message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_validation_rules', to='master_data_import.importtemplate')),
            ],
            options={
                'verbose_name': 'Import Validation Rule',
                'verbose_name_plural': 'Import Validation Rules',
                'ordering': ['template', 'field_name'],
            },
        ),
    ]
