# Generated by Django 5.0.2 on 2025-08-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data_import', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportError',
            new_name='ImportDataError',
        ),
    ]
